export const PRODUCT_CATEGORIES = [
  "Grocery",
  "Fresh Food",
  "Frozen Food",
  "Household",
  "Personal Care",
  "Beauty & Cosmetics",
  "Baby Care",
  "Medicine & Health",
  "School & Office Supplies",
  "Hardware",
  "Home Improvement",
  "Electronics",
  "Appliances",
  "Automotive",
  "Pet Supplies",
  "Clothing & Accessories",
  "Kitchen & Dining",
  "Home & Living",
  "Sports & Outdoors",
  "Toys & Games",
  "Garden & Agriculture",
  "Party & Events",
  "Books & Media",
  "Tobacco Accessories",
  "Religious & Cultural Items",
  "Services & Fees",
  "Other",
];