export const PRODUCT_SUBCATEGORIES: Record<
  string,
  string[]
> = {

  Grocery: [
    "Rice", "Grains", "Flour", "Bread & Bakery", "Cakes & Pastries",
    "Breakfast Cereals", "Oatmeal", "Instant Noodles", "Pasta", "Pasta Sauce",
    "Canned Fish", "Canned Meat", "Canned Vegetables", "Canned Fruits",
    "Canned Meals", "Processed Meat", "Dried Fish", "Dried Food",
    "Cooking Oil", "Vinegar", "Soy Sauce", "Fish Sauce", "Condiments",
    "Seasonings", "Herbs & Spices", "Salt", "Sugar", "Sweeteners",
    "Baking Supplies", "Baking Mixes", "Dessert Mixes", "Soup & Broth",
    "Instant Meals", "Ready-to-Eat Meals", "Snacks", "Chips", "Crackers",
    "Biscuits", "Cookies", "Popcorn", "Nuts & Seeds", "Dried Fruits",
    "Candy", "Chocolate", "Gum & Mints", "Spreads", "Peanut Butter",
    "Jams & Preserves", "Honey", "Dairy Milk", "Powdered Milk",
    "Evaporated Milk", "Condensed Milk", "Plant-Based Milk", "Cream",
    "Cheese", "Yogurt", "Butter & Margarine", "Eggs", "Coffee", "Tea",
    "Chocolate Drinks", "Powdered Drinks", "Soft Drinks", "Juices",
    "Bottled Water", "Sparkling Water", "Energy Drinks", "Sports Drinks",
    "Milk Drinks", "Ready-to-Drink Coffee", "Ready-to-Drink Tea",
    "Alcoholic Beverages", "Beer", "Wine", "Spirits", "Cocktail Mixers",
    "Diet & Specialty Food", "Organic Food", "Gluten-Free Food",
    "Sugar-Free Food", "Vegetarian & Vegan Food", "International Food"
  ],

  "Fresh Food": [
    "Fresh Vegetables", "Leafy Vegetables", "Root Crops", "Fresh Fruits",
    "Citrus Fruits", "Tropical Fruits", "Fresh Meat", "Beef", "Pork",
    "Chicken", "Turkey", "Duck", "Seafood", "Fish", "Shrimp", "Crab",
    "Shellfish", "Fresh Herbs", "Fresh Mushrooms", "Fresh Eggs",
    "Fresh Dairy", "Fresh Tofu"
  ],

  "Frozen Food": [
    "Frozen Meat", "Frozen Seafood", "Frozen Vegetables",
    "Frozen Fruits", "Frozen Meals", "Frozen Pizza",
    "Frozen Dumplings", "Frozen Snacks", "Ice Cream",
    "Frozen Desserts"
  ],

  Household: [
    "Laundry Detergent", "Laundry Soap", "Fabric Conditioner", "Bleach",
    "Stain Remover", "Laundry Additives", "Dishwashing Liquid",
    "Dishwashing Paste", "Dishwasher Detergent", "Dishwashing Sponges",
    "Scrubbers", "Floor Cleaner", "Toilet Cleaner", "Bathroom Cleaner",
    "Glass Cleaner", "Kitchen Cleaner", "Multipurpose Cleaner",
    "Disinfectant", "Furniture Polish", "Metal Polish", "Drain Cleaner",
    "Mold & Mildew Remover", "Air Freshener", "Dehumidifier",
    "Moisture Absorber", "Insecticide", "Mosquito Repellent",
    "Pest Control", "Garbage Bags", "Trash Bins", "Paper Towels",
    "Facial Tissue", "Toilet Paper", "Table Napkins",
    "Aluminum Foil", "Plastic Wrap", "Wax Paper", "Baking Paper",
    "Food Storage Bags", "Food Storage Containers", "Straws",
    "Cleaning Cloths", "Mops", "Brooms", "Dustpans", "Brushes",
    "Buckets", "Cleaning Gloves", "Cleaning Tools",
    "Clothes Hangers", "Clothespins", "Laundry Baskets",
    "Ironing Supplies", "Shoe Care", "Matches",
    "Emergency Supplies"
  ],

  "Personal Care": [
    "Soap", "Body Wash", "Shampoo", "Conditioner",
    "Hair Treatment", "Hair Color", "Hair Styling",
    "Toothpaste", "Toothbrush", "Dental Floss",
    "Mouthwash", "Feminine Care", "Sanitary Napkins",
    "Panty Liners", "Tampons", "Adult Diapers",
    "Baby Wipes", "Tissues", "Wet Wipes",
    "Cotton Balls", "Cotton Buds",
    "Hand Sanitizer", "Disposable Gloves",
    "Deodorant", "Perfume", "Cologne", "Body Spray",
    "Body Lotion", "Body Cream", "Petroleum Jelly",
    "Hand Cream", "Foot Care",
    "Shaving Cream", "Razors", "Aftershave",
    "Nail Clippers", "Nail Care", "Combs",
    "Hair Brushes", "Bath Accessories", "Travel Toiletries"
  ],

  "Beauty & Cosmetics": [
    "Makeup", "Foundation", "BB Cream", "CC Cream", "Concealer",
    "Face Powder", "Pressed Powder", "Loose Powder", "Blush",
    "Bronzer", "Highlighter", "Contour", "Makeup Primer", "Setting Spray",
    "Lipstick", "Lip Tint", "Lip Gloss", "Lip Liner", "Lip Balm",
    "Mascara", "Eyeliner", "Eyebrow Pencil", "Eyebrow Gel",
    "Eyeshadow", "False Eyelashes", "Eyelash Glue",
    "Makeup Remover", "Micellar Water", "Facial Cleanser",
    "Facial Wash", "Face Toner", "Face Serum", "Face Cream",
    "Moisturizer", "Sunscreen", "Sunblock", "Face Mask",
    "Exfoliator", "Facial Scrub", "Acne Treatment",
    "Anti-Aging", "Beauty Tools", "Makeup Brushes",
    "Beauty Sponges", "Cotton Pads", "Nail Polish",
    "Nail Polish Remover", "Artificial Nails", "Cuticle Care",
    "Body Mist"
  ],

  "Baby Care": [
    "Baby Formula", "Baby Food", "Baby Cereal", "Baby Snacks",
    "Baby Bottles", "Bottle Nipples", "Bottle Cleaners",
    "Bottle Sterilizers", "Baby Diapers", "Training Pants",
    "Baby Powder", "Baby Lotion",
    "Baby Shampoo", "Baby Soap", "Baby Wash",
    "Baby Oil", "Baby Cream", "Diaper Rash Cream",
    "Pacifiers", "Teethers", "Baby Utensils",
    "Baby Bibs", "Baby Clothing", "Baby Blankets",
    "Baby Towels", "Baby Bath Accessories",
    "Baby Toys", "Baby Safety", "Baby Feeding Accessories"
  ],

  "Medicine & Health": [
    "Pain Relief", "Fever Medicine", "Cold Medicine",
    "Cough Medicine", "Flu Medicine", "Allergy Medicine",
    "Antibiotics", "Antifungal", "Antiviral",
    "Antiseptics", "Vitamins", "Multivitamins",
    "Vitamin C", "Vitamin D", "Calcium",
    "Iron Supplements", "Fish Oil", "Herbal Supplements",
    "Digestive Health", "Probiotics", "Antacids",
    "Diarrhea Medicine", "Laxatives", "Medical Supplies",
    "Bandages", "Gauze", "Medical Tape",
    "Cotton", "Hydrogen Peroxide", "Rubbing Alcohol",
    "Betadine", "Thermometers", "Blood Pressure Monitors",
    "Blood Sugar Monitors", "Nebulizers", "Face Masks",
    "Medical Gloves", "First Aid Kits", "Prescription Medicine",
    "Over-the-Counter Medicine", "Eye Drops",
    "Ear Drops", "Nasal Spray"
  ],

  "School & Office Supplies": [
    "Notebooks", "Writing Pads", "Loose Leaf Paper",
    "Bond Paper", "Colored Paper", "Index Cards",
    "Pens", "Ballpens", "Gel Pens", "Markers",
    "Highlighters", "Pencils", "Mechanical Pencils",
    "Colored Pencils", "Crayons", "Oil Pastels", "Watercolors",
    "Erasers", "Sharpeners", "Correction Tape",
    "Correction Fluid", "Glue", "Glue Sticks",
    "Scissors", "Rulers", "Protractors",
    "Compasses", "Staplers", "Staples",
    "Paper Clips", "Binder Clips", "Folders",
    "Envelopes", "Binders", "Document Holders",
    "Whiteboards", "Whiteboard Markers", "Chalk",
    "Calculators", "Desk Organizers", "Sticky Notes",
    "Labels", "Printer Ink", "Printer Toner",
    "Printer Paper", "Laminating Supplies",
    "Office Chairs", "Office Accessories",
    "School Bags", "Lunch Boxes"
  ],

  Hardware: [
    "Hand Tools", "Power Tools", "Tool Sets", "Tool Storage",
    "Hammers", "Screwdrivers", "Wrenches", "Pliers",
    "Sockets", "Allen Keys", "Tape Measures", "Levels",
    "Utility Knives", "Hand Saws", "Chisels", "Files",
    "Clamps", "Vises", "Drill Bits", "Saw Blades",
    "Grinding Discs", "Sandpaper", "Wire Brushes",
    "Nails", "Concrete Nails", "Finishing Nails",
    "Roofing Nails", "Screws", "Wood Screws",
    "Machine Screws", "Self-Tapping Screws",
    "Drywall Screws", "Bolts & Nuts",
    "Washers", "Anchors", "Wall Plugs",
    "Rivets", "Fasteners", "Chains", "Hooks",
    "Eye Bolts", "Turnbuckles", "Cable Ties",
    "Ropes", "Steel Wires", "Adhesives",
    "Super Glue", "Epoxy", "Wood Glue",
    "Construction Adhesive", "Sealants",
    "Silicone Sealant", "Caulking",
    "Thread Seal Tape", "Paint",
    "Paint Primer", "Wood Stain", "Varnish",
    "Paint Thinner", "Paint Remover",
    "Painting Supplies", "Paint Brushes",
    "Paint Rollers", "Paint Trays",
    "Masking Tape", "Drop Cloths",
    "Electrical Supplies", "Electrical Wires",
    "Electrical Cables", "Extension Cords",
    "Electrical Tape", "Circuit Breakers",
    "Fuses", "Wall Switches", "Electrical Outlets",
    "Light Bulbs", "LED Bulbs", "Lamp Holders",
    "Junction Boxes", "Conduits",
    "Plumbing Supplies", "PVC Pipes & Fittings",
    "PPR Pipes & Fittings", "GI Pipes",
    "Pipe Clamps", "Pipe Sealants",
    "Pipe Insulation", "Faucets",
    "Shower Heads", "Water Hoses",
    "Garden Hoses", "Hose Connectors",
    "Valves", "Water Pumps",
    "Construction Materials", "Cement",
    "Concrete Mix", "Sand", "Gravel",
    "Bricks", "Hollow Blocks",
    "Roofing Sheets", "Metal Sheets",
    "Steel Bars", "Plywood", "Lumber",
    "Insulation Materials", "Roof Sealants",
    "Safety Equipment", "Hard Hats",
    "Safety Glasses", "Face Shields",
    "Ear Protection", "Work Gloves",
    "Safety Shoes", "Safety Harnesses",
    "Reflective Vests", "Respirators",
    "Dust Masks", "Fire Extinguishers",
    "Locks", "Padlocks", "Door Locks",
    "Deadbolts", "Combination Locks",
    "Smart Locks", "Keys",
    "Hinges", "Door Closers",
    "Drawer Slides", "Cabinet Handles",
    "Cabinet Knobs", "Furniture Casters",
    "Gardening Tools", "Shovels",
    "Spades", "Rakes", "Garden Hoes",
    "Pruning Shears", "Grass Cutters",
    "Wheelbarrows", "Sprayers", "Watering Cans"
  ],

  "Home Improvement": [
    "Flooring", "Tiles", "Vinyl Flooring",
    "Laminate Flooring", "Wood Flooring",
    "Wallpaper", "Wall Panels",
    "Ceiling Panels", "Roofing Materials",
    "Doors", "Windows", "Window Blinds",
    "Kitchen Cabinets", "Bathroom Fixtures", "Sinks",
    "Toilets", "Bathtubs", "Bathroom Accessories",
    "Furniture Hardware", "Home Security", "Door Bells",
    "CCTV Accessories", "Smoke Detectors",
    "Carbon Monoxide Detectors",
    "Home Automation", "Smart Lighting",
    "Smart Plugs", "Smart Sensors"
  ],

  Electronics: [
    "Mobile Phones", "Smartphones",
    "Feature Phones", "Tablets",
    "Laptops", "Desktop Computers",
    "Computer Monitors", "Mini PCs",
    "Keyboards", "Mechanical Keyboards",
    "Mice", "Mouse Pads",
    "Webcams", "Microphones",
    "Headphones", "Earphones",
    "Wireless Earbuds", "Speakers",
    "Bluetooth Speakers",
    "Power Banks", "Chargers",
    "Charging Cables", "USB Cables",
    "Lightning Cables", "USB Hubs",
    "Adapters", "Power Adapters",
    "Extension Outlets", "Surge Protectors",
    "Memory Cards", "USB Flash Drives",
    "External Hard Drives", "SSDs",
    "Computer Components", "Processors",
    "Motherboards", "Graphics Cards",
    "RAM", "Power Supplies",
    "Computer Cases", "Cooling Fans",
    "Thermal Paste", "Networking Devices",
    "Wi-Fi Routers", "Wi-Fi Extenders",
    "Network Switches", "Modems",
    "LAN Cables", "HDMI Cables",
    "DisplayPort Cables",
    "Televisions", "TV Boxes",
    "Streaming Devices", "Projectors",
    "Printers", "Scanners",
    "Printer Accessories",
    "Security Cameras", "CCTV Systems",
    "Smart Watches", "Fitness Trackers",
    "Drones", "VR Headsets",
    "Electronic Components",
    "Breadboards", "Resistors",
    "Capacitors", "Transistors",
    "Microcontrollers", "Arduino Boards",
    "ESP32 Boards", "Raspberry Pi",
    "Sensors", "Relays",
    "Servo Motors", "Stepper Motors",
    "LCD Displays", "OLED Displays"
  ],

  Appliances: [
    "Refrigerators", "Freezers",
    "Air Conditioners", "Electric Fans",
    "Stand Fans", "Desk Fans",
    "Ceiling Fans", "Exhaust Fans",
    "Washing Machines", "Dryers",
    "Clothes Drying Cabinets",
    "Microwave Ovens", "Electric Ovens",
    "Toaster Ovens", "Rice Cookers",
    "Pressure Cookers", "Slow Cookers",
    "Multi Cookers", "Induction Cookers",
    "Electric Stoves", "Gas Stoves",
    "Range Hoods", "Coffee Makers",
    "Espresso Machines", "Electric Kettles",
    "Water Dispensers", "Water Purifiers",
    "Blenders", "Food Processors",
    "Mixers", "Juicers",
    "Air Fryers", "Deep Fryers",
    "Sandwich Makers", "Waffle Makers",
    "Bread Makers", "Ice Makers",
    "Vacuum Cleaners", "Robot Vacuums",
    "Steam Cleaners", "Garment Steamers",
    "Irons", "Hair Dryers",
    "Hair Straighteners", "Curling Irons",
    "Dehumidifiers", "Humidifiers",
    "Air Purifiers", "Electric Heaters",
    "Water Heaters", "Sewing Machines"
  ],

  Automotive: [
    "Engine Oil", "Transmission Fluid", "Brake Fluid", "Coolant",
    "Radiator Fluid", "Power Steering Fluid", "Gear Oil",
    "Fuel Additives", "Engine Additives", "Grease", "Lubricants",
    "Car Batteries", "Battery Chargers", "Battery Terminals",
    "Battery Accessories", "Spark Plugs", "Ignition Coils",
    "Air Filters", "Oil Filters", "Fuel Filters", "Cabin Filters",
    "Windshield Wipers", "Wiper Blades", "Headlights",
    "Fog Lights", "Tail Lights", "Signal Lights",
    "Automotive Bulbs", "Car Fuses",
    "Tires", "Inner Tubes", "Wheel Rims",
    "Wheel Covers", "Tire Repair Kits", "Air Compressors",
    "Jacks", "Jack Stands", "Jumper Cables",
    "Tow Ropes", "Emergency Kits", "Car Tools",
    "Seat Covers", "Floor Mats", "Steering Wheel Covers",
    "Car Organizers", "Dash Cameras", "Phone Holders",
    "Car Chargers", "Car Audio",
    "Amplifiers", "Subwoofers", "Cleaning Supplies",
    "Car Shampoo", "Wax", "Polish",
    "Microfiber Cloths", "Glass Cleaners",
    "Pressure Washers", "Motorcycle Parts",
    "Motorcycle Helmets", "Motorcycle Accessories"
  ],

  "Pet Supplies": [
    "Dog Food", "Cat Food", "Fish Food",
    "Bird Food", "Rabbit Food", "Hamster Food",
    "Pet Treats", "Pet Vitamins", "Pet Supplements",
    "Pet Medicine", "Pet Shampoo", "Pet Conditioner",
    "Pet Soap", "Pet Wipes", "Pet Grooming",
    "Pet Brushes", "Pet Nail Clippers",
    "Pet Toothpaste", "Pet Toothbrush",
    "Pet Collars", "Pet Leashes", "Pet Harnesses",
    "Pet Clothing", "Pet Beds", "Pet Blankets",
    "Pet Toys", "Chew Toys", "Scratching Posts",
    "Cat Litter", "Litter Boxes", "Litter Scoops",
    "Pet Bowls", "Pet Feeders", "Pet Water Dispensers",
    "Aquariums", "Aquarium Filters", "Aquarium Decorations",
    "Aquarium Pumps", "Aquarium Lighting",
    "Bird Cages", "Dog Cages", "Pet Carriers",
    "Pet Training", "Pet Cleaning Supplies"
  ],

  "Clothing & Accessories": [
    "Shirts", "T-Shirts", "Polo Shirts",
    "Blouses", "Dresses", "Skirts",
    "Jeans", "Pants", "Shorts",
    "Leggings", "Jackets", "Coats",
    "Sweaters", "Hoodies", "Undergarments",
    "Bras", "Panties", "Boxers",
    "Socks", "Sleepwear", "Swimwear",
    "Activewear", "School Uniforms", "Work Uniforms",
    "Children's Clothing", "Maternity Wear",
    "Shoes", "Sandals", "Slippers",
    "Boots", "Sneakers", "Heels",
    "Caps", "Hats", "Belts",
    "Wallets", "Handbags", "Backpacks",
    "Luggage", "Scarves", "Gloves",
    "Jewelry", "Necklaces", "Bracelets",
    "Rings", "Earrings", "Watches",
    "Sunglasses", "Hair Accessories",
    "Fashion Accessories"
  ],

  "Kitchen & Dining": [
    "Cookware", "Frying Pans", "Saucepans", "Stock Pots",
    "Bakeware", "Baking Trays", "Cake Pans",
    "Mixing Bowls", "Measuring Cups",
    "Measuring Spoons", "Kitchen Utensils",
    "Spatulas", "Ladles", "Tongs",
    "Whisks", "Can Openers", "Bottle Openers",
    "Knives", "Knife Sets", "Cutting Boards",
    "Kitchen Shears", "Graters", "Peelers",
    "Colanders", "Strainers", "Food Containers",
    "Food Storage", "Lunch Containers",
    "Water Bottles", "Tumblers", "Mugs",
    "Cups", "Glasses", "Plates",
    "Bowls", "Serving Platters", "Serving Trays",
    "Serving Utensils", "Dinnerware",
    "Flatware", "Spoons", "Forks",
    "Chopsticks", "Table Knives",
    "Tablecloths", "Placemats", "Napkins",
    "Kitchen Towels", "Oven Mitts"
  ],

  "Home & Living": [
    "Furniture", "Sofas", "Chairs",
    "Tables", "Dining Tables", "Coffee Tables",
    "Beds", "Mattresses", "Bed Frames",
    "Wardrobes", "Cabinets", "Shelves",
    "Bookcases", "Storage Boxes",
    "Storage Baskets", "Closet Organizers",
    "Curtains", "Curtain Rods",
    "Blinds", "Rugs", "Carpets",
    "Doormats", "Pillows", "Cushions",
    "Bedsheets", "Blankets", "Comforters",
    "Quilts", "Mattress Protectors",
    "Decorations", "Wall Art", "Picture Frames",
    "Mirrors", "Vases", "Artificial Plants",
    "Indoor Plants", "Clocks", "Lamps",
    "Table Lamps", "Floor Lamps",
    "Ceiling Lights", "LED Strips",
    "Scented Candles", "Diffusers", "Home Fragrance",
    "Laundry Hampers", "Shoe Racks",
    "Storage Cabinets"
  ],

  "Sports & Outdoors": [
    "Basketballs", "Volleyballs", "Footballs", "Soccer Balls",
    "Baseballs", "Softballs", "Badminton Rackets", "Badminton Shuttlecocks",
    "Tennis Rackets", "Tennis Balls", "Table Tennis Paddles",
    "Table Tennis Balls", "Golf Clubs", "Golf Balls",
    "Boxing Gloves", "Punching Bags", "Protective Gear",
    "Helmets", "Knee Pads", "Elbow Pads", "Sports Bags",
    "Sports Bottles", "Fitness Equipment", "Dumbbells",
    "Barbells", "Weight Plates", "Resistance Bands",
    "Yoga Mats", "Yoga Blocks", "Jump Ropes",
    "Exercise Bikes", "Treadmills", "Camping Tents",
    "Sleeping Bags", "Camping Chairs", "Camping Tables",
    "Flashlights", "Lanterns", "Coolers",
    "Picnic Supplies", "Hiking Backpacks", "Trekking Poles",
    "Fishing Rods", "Fishing Reels", "Fishing Lines",
    "Fishing Hooks", "Fishing Baits", "Life Jackets",
    "Swimming Goggles", "Swimming Caps", "Beach Accessories",
    "Bicycles", "Bike Helmets", "Bike Accessories"
  ],

  "Toys & Games": [
    "Action Figures", "Dolls", "Stuffed Toys",
    "Building Blocks", "Construction Toys", "Toy Cars",
    "Toy Trucks", "Toy Trains", "Remote Control Toys",
    "Educational Toys", "Learning Toys", "Board Games",
    "Card Games", "Puzzles", "Jigsaw Puzzles",
    "Chess Sets", "Checkers", "Rubik's Cubes",
    "Musical Toys", "Toy Instruments", "Pretend Play",
    "Kitchen Playsets", "Doctor Playsets",
    "Tool Playsets", "Outdoor Toys", "Water Guns",
    "Kites", "Bubbles", "Play Dough",
    "Slime", "Arts & Crafts",
    "Toy Storage", "Collectibles", "Trading Cards",
    "Video Games", "Gaming Consoles",
    "Gaming Accessories"
  ],

  "Garden & Agriculture": [
    "Garden Soil", "Potting Mix", "Compost",
    "Fertilizers", "Organic Fertilizers",
    "Chemical Fertilizers", "Seeds",
    "Vegetable Seeds", "Flower Seeds",
    "Fruit Seeds", "Seedlings",
    "Pesticides", "Herbicides", "Fungicides",
    "Plant Nutrients", "Plant Pots",
    "Planters", "Seed Trays", 
    "Hose Nozzles", "Sprinklers", "Irrigation Supplies",
    "Garden Gloves", "Garden Shovels", "Garden Rakes",
     "Chainsaws", "Leaf Blowers", "Greenhouses",
    "Livestock Feed", "Poultry Feed",
    "Animal Supplements", "Farm Tools",
    "Agricultural Equipment"
  ],

  "Party & Events": [
    "Balloons", "Balloon Accessories",
    "Party Hats", "Party Decorations",
    "Banners", "Streamers", "Confetti",
    "Cake Toppers", "Birthday Candles", "Gift Wrap",
    "Gift Bags", "Gift Boxes",
    "Gift Ribbons", "Greeting Cards",
    "Invitations", "Disposable Plates",
    "Disposable Cups", "Disposable Cutlery",
    "Table Covers", "Party Favors",
    "Photo Booth Props", "Costumes",
    "Masks", "Event Decorations",
    "Wedding Supplies", "Baby Shower Supplies",
    "Christmas Decorations", "Halloween Decorations"
  ],

  "Books & Media": [
    "Books", "Novels", "Textbooks",
    "Reference Books", "Children's Books",
    "Comic Books", "Magazines", "Newspapers",
    "Journals", "Coloring Books",
    "Planners", "Calendars", "Maps",
    "DVDs", "Blu-rays", "Music CDs",
    "Vinyl Records", "Gift Cards"
  ],

  "Tobacco Accessories": [
    "Cigarettes", "Cigars", "Rolling Papers",
    "Cigarette Filters", "Lighters",
    "Ashtrays", "Cigarette Cases", "Humidors",
    "Pipe Tobacco", "Smoking Pipes"
  ],

  "Religious & Cultural Items": [
    "Bibles", "Prayer Books",
    "Rosaries", "Crosses",
    "Religious Statues", "Candles",
    "Incense", "Incense Holders",
    "Holy Water Bottles",
    "Religious Jewelry",
    "Offering Envelopes",
    "Religious Decorations",
    "Cultural Decorations",
    "Festival Supplies"
  ],

  "Services & Fees": [
    "Delivery Fees", "Service Charges",
    "Membership Fees", "Subscriptions",
    "Gift Wrapping", "Installation Services",
    "Repair Services", "Warranty Services",
    "Rental Fees", "Processing Fees",
    "Shipping Fees", "Convenience Fees"
  ],

  Other: [
    "Uncategorized", "Miscellaneous",
    "Unknown", "Custom Items",
    "Seasonal Items", "Limited Edition",
    "Promotional Items", "Bundles",
    "Clearance Items", "Refurbished Items"
  ],

};