export const SUBCATEGORY_ALIASES: Record<string, string[]> = {
 // GROCERY
  "Grocery::Rice": ["bigas", "white rice", "brown rice", "jasmine rice"],
  "Grocery::Grains": ["grain", "whole grain", "cereal grains"],
  "Grocery::Flour": ["all purpose flour", "all-purpose flour", "wheat flour"],
  "Grocery::Bread & Bakery": ["bread", "bakery products", "baked goods", "bread and bakery"],
  "Grocery::Cakes & Pastries": ["cake", "pastry", "pastries", "cakes and pastries", "cakes & pastry"],
  "Grocery::Breakfast Cereals": ["cereal", "corn flakes", "breakfast cereal"],
  "Grocery::Oatmeal": ["oats", "rolled oats", "instant oats"],
  "Grocery::Instant Noodles": ["noodles", "instant noodle", "cup noodles", "pancit canton"],
  "Grocery::Pasta": ["spaghetti", "macaroni", "noodles"],
  "Grocery::Pasta Sauce": ["spaghetti sauce", "tomato pasta sauce"],
  "Grocery::Canned Fish": ["sardines", "canned tuna", "canned seafood"],
  "Grocery::Canned Meat": ["corned beef", "luncheon meat", "meat loaf"],
  "Grocery::Canned Vegetables": ["canned veggies", "tinned vegetables", "canned vegetable"],
  "Grocery::Canned Fruits": ["tinned fruits", "fruit cocktail", "canned fruit"],
  "Grocery::Canned Meals": ["ready meal", "tinned meal", "canned meal"],
  "Grocery::Processed Meat": ["hotdog", "sausage", "ham"],
  "Grocery::Dried Fish": ["tuyo", "daing", "dried seafood"],
  "Grocery::Dried Food": ["dehydrated food", "dry food"],
  "Grocery::Cooking Oil": ["vegetable oil", "canola oil", "coconut oil"],
  "Grocery::Vinegar": ["suka", "cane vinegar", "white vinegar"],
  "Grocery::Soy Sauce": ["toyo", "soya sauce"],
  "Grocery::Fish Sauce": ["patis"],
  "Grocery::Condiments": ["sauces", "table sauce", "condiment"],
  "Grocery::Seasonings": ["seasoning", "flavoring"],
  "Grocery::Herbs & Spices": ["herbs and spices", "spices", "herbs", "herbs & spice"],
  "Grocery::Salt": ["asin", "iodized salt", "rock salt"],
  "Grocery::Sugar": ["asukal", "white sugar", "brown sugar"],
  "Grocery::Sweeteners": ["sweetener", "sugar substitute"],
  "Grocery::Baking Supplies": ["baking ingredients", "baking needs", "baking supply"],
  "Grocery::Baking Mixes": ["cake mix", "baking premix", "baking mix"],
  "Grocery::Dessert Mixes": ["dessert mix", "gelatin mix", "pudding mix"],
  "Grocery::Soup & Broth": ["soup and broth", "soup", "broth"],
  "Grocery::Instant Meals": ["instant meal", "quick meal"],
  "Grocery::Ready-to-Eat Meals": ["ready to eat meals", "prepared meals", "rte meals", "ready-to-eat meal"],
  "Grocery::Snacks": ["snack", "meryenda"],
  "Grocery::Chips": ["potato chips", "corn chips", "crisps", "chip"],
  "Grocery::Crackers": ["cracker"],
  "Grocery::Biscuits": ["biscuit"],
  "Grocery::Cookies": ["cookie"],
  "Grocery::Popcorn": ["popped corn"],
  "Grocery::Nuts & Seeds": ["nuts and seeds", "nuts", "seeds", "nuts & seed"],
  "Grocery::Dried Fruits": ["dried fruit", "dehydrated fruits"],
  "Grocery::Candy": ["candies", "sweets"],
  "Grocery::Chocolate": ["chocolates", "chocolate bar"],
  "Grocery::Gum & Mints": ["gum and mints", "chewing gum", "mints", "gum & mint"],
  "Grocery::Spreads": ["sandwich spread", "bread spread", "spread"],
  "Grocery::Peanut Butter": ["peanut spread"],
  "Grocery::Jams & Preserves": ["jams and preserves", "fruit jam", "preserves", "jams & preserve"],
  "Grocery::Honey": ["pure honey"],
  "Grocery::Dairy Milk": ["fresh milk", "cow milk"],
  "Grocery::Powdered Milk": ["milk powder", "dry milk"],
  "Grocery::Evaporated Milk": ["evap milk"],
  "Grocery::Condensed Milk": ["sweetened condensed milk", "condensada"],
  "Grocery::Plant-Based Milk": ["plant based milk", "non dairy milk", "vegan milk"],
  "Grocery::Cream": ["all purpose cream", "dairy cream"],
  "Grocery::Cheese": ["processed cheese", "cheddar"],
  "Grocery::Yogurt": ["yoghurt"],
  "Grocery::Butter & Margarine": ["butter and margarine", "butter", "margarine"],
  "Grocery::Eggs": ["egg"],
  "Grocery::Coffee": ["instant coffee", "coffee mix", "3 in 1 coffee"],
  "Grocery::Tea": ["tea bag", "green tea", "black tea"],
  "Grocery::Chocolate Drinks": ["chocolate drink", "cocoa drink"],
  "Grocery::Powdered Drinks": ["powdered drink", "drink mix", "juice powder"],
  "Grocery::Soft Drinks": ["soft drink", "soda", "cola"],
  "Grocery::Juices": ["juice", "fruit juice"],
  "Grocery::Bottled Water": ["drinking water", "mineral water"],
  "Grocery::Sparkling Water": ["carbonated water", "soda water"],
  "Grocery::Energy Drinks": ["energy drink"],
  "Grocery::Sports Drinks": ["sports drink", "electrolyte drink"],
  "Grocery::Milk Drinks": ["milk drink", "flavored milk"],
  "Grocery::Ready-to-Drink Coffee": ["ready to drink coffee", "rtd coffee", "bottled coffee"],
  "Grocery::Ready-to-Drink Tea": ["ready to drink tea", "rtd tea", "bottled tea"],
  "Grocery::Alcoholic Beverages": ["alcoholic drinks", "liquor", "alcoholic beverage"],
  "Grocery::Beer": ["beer"],
  "Grocery::Wine": ["wine"],
  "Grocery::Spirits": ["spirit"],
  "Grocery::Cocktail Mixers": ["cocktail mixer", "drink mixer"],
  "Grocery::Baby Food": ["infant food"],
  "Grocery::Diet & Specialty Food": ["diet and specialty food", "special diet food"],
  "Grocery::Organic Food": ["organic products"],
  "Grocery::Gluten-Free Food": ["gluten free food"],
  "Grocery::Sugar-Free Food": ["sugar free food"],
  "Grocery::Vegetarian & Vegan Food": ["vegetarian and vegan food", "vegan food"],
  "Grocery::International Food": ["imported food", "world food"],

  // FRESH FOOD
  "Fresh Food::Fresh Vegetables": ["vegetables", "fresh veggies", "gulay", "fresh vegetable"],
  "Fresh Food::Leafy Vegetables": ["leafy greens", "green vegetables", "leafy vegetable"],
  "Fresh Food::Root Crops": ["root vegetables", "root crop"],
  "Fresh Food::Fresh Fruits": ["fruits", "fresh fruit", "prutas"],
  "Fresh Food::Citrus Fruits": ["citrus fruit"],
  "Fresh Food::Tropical Fruits": ["tropical fruit"],
  "Fresh Food::Fresh Meat": ["raw meat", "meat"],
  "Fresh Food::Beef": ["beef meat"],
  "Fresh Food::Pork": ["pork meat"],
  "Fresh Food::Chicken": ["chicken meat", "poultry"],
  "Fresh Food::Turkey": ["turkey"],
  "Fresh Food::Duck": ["duck"],
  "Fresh Food::Seafood": ["sea food"],
  "Fresh Food::Fish": ["fish"],
  "Fresh Food::Shrimp": ["prawn", "prawns", "hipon"],
  "Fresh Food::Crab": ["crabs", "alimango"],
  "Fresh Food::Shellfish": ["shell fish"],
  "Fresh Food::Fresh Herbs": ["culinary herbs", "fresh herb"],
  "Fresh Food::Fresh Mushrooms": ["mushroom", "fresh mushroom"],
  "Fresh Food::Fresh Eggs": ["fresh egg"],
  "Fresh Food::Fresh Dairy": ["fresh dairy products"],
  "Fresh Food::Fresh Tofu": ["tofu", "bean curd"],

  // FROZEN FOOD
  "Frozen Food::Frozen Meat": ["frozen meat"],
  "Frozen Food::Frozen Seafood": ["frozen fish", "frozen sea food"],
  "Frozen Food::Frozen Vegetables": ["frozen veggies", "frozen vegetable"],
  "Frozen Food::Frozen Fruits": ["frozen fruit"],
  "Frozen Food::Frozen Meals": ["frozen ready meals", "frozen meal"],
  "Frozen Food::Frozen Pizza": ["frozen pizza"],
  "Frozen Food::Frozen Dumplings": ["dumplings", "siomai", "frozen dumpling"],
  "Frozen Food::Frozen Snacks": ["frozen snack"],
  "Frozen Food::Ice Cream": ["icecream"],
  "Frozen Food::Frozen Desserts": ["frozen dessert"],

  // HOUSEHOLD
  "Household::Laundry Detergent": ["detergent", "washing powder", "laundry powder"],
  "Household::Laundry Soap": ["washing soap", "laundry bar"],
  "Household::Fabric Conditioner": ["fabric softener"],
  "Household::Bleach": ["chlorine bleach", "laundry bleach"],
  "Household::Stain Remover": ["spot remover"],
  "Household::Laundry Additives": ["laundry booster", "wash additive", "laundry additive"],
  "Household::Dishwashing Liquid": ["dish soap", "dishwashing soap", "dish wash"],
  "Household::Dishwashing Paste": ["dish paste"],
  "Household::Dishwasher Detergent": ["dishwasher soap"],
  "Household::Dishwashing Sponges": ["dish sponge", "kitchen sponge", "dishwashing sponge"],
  "Household::Scrubbers": ["scrubber", "scouring pad"],
  "Household::Floor Cleaner": ["floor cleaning solution"],
  "Household::Toilet Cleaner": ["toilet bowl cleaner"],
  "Household::Bathroom Cleaner": ["bathroom cleaning solution"],
  "Household::Glass Cleaner": ["window cleaner"],
  "Household::Kitchen Cleaner": ["kitchen cleaning solution"],
  "Household::Multipurpose Cleaner": ["multi purpose cleaner", "all purpose cleaner"],
  "Household::Disinfectant": ["disinfectant spray", "surface disinfectant"],
  "Household::Furniture Polish": ["wood polish"],
  "Household::Metal Polish": ["metal cleaner"],
  "Household::Drain Cleaner": ["drain opener"],
  "Household::Mold & Mildew Remover": ["mold and mildew remover", "mould remover"],
  "Household::Air Freshener": ["room freshener", "air fragrance"],
  "Household::Dehumidifier": ["moisture remover"],
  "Household::Moisture Absorber": ["dehumidifying absorber"],
  "Household::Insecticide": ["bug spray", "insect spray"],
  "Household::Mosquito Repellent": ["mosquito spray", "mosquito coil"],
  "Household::Pest Control": ["pesticide", "pest killer"],
  "Household::Garbage Bags": ["trash bags", "bin liners", "garbage bag"],
  "Household::Trash Bins": ["garbage bin", "waste bin", "trash bin"],
  "Household::Paper Towels": ["kitchen towels", "paper towel"],
  "Household::Facial Tissue": ["face tissue", "tissue"],
  "Household::Toilet Paper": ["bathroom tissue", "tissue roll"],
  "Household::Table Napkins": ["table napkin", "paper napkins"],
  "Household::Wet Wipes": ["wet tissue", "moist wipes", "wet wipe"],
  "Household::Aluminum Foil": ["aluminium foil", "foil"],
  "Household::Plastic Wrap": ["cling wrap", "cling film"],
  "Household::Wax Paper": ["waxed paper"],
  "Household::Baking Paper": ["parchment paper"],
  "Household::Food Storage Bags": ["zip bags", "food bags", "food storage bag"],
  "Household::Food Storage Containers": ["food container", "storage container", "tupperware", "food storage container"],
  "Household::Disposable Plates": ["paper plates", "plastic plates", "disposable plate"],
  "Household::Disposable Cups": ["paper cups", "plastic cups", "disposable cup"],
  "Household::Disposable Cutlery": ["plastic utensils", "disposable utensils"],
  "Household::Straws": ["straw"],
  "Household::Cleaning Cloths": ["cleaning rags", "cleaning cloth"],
  "Household::Mops": ["mop"],
  "Household::Brooms": ["broom", "walis"],
  "Household::Dustpans": ["dustpan"],
  "Household::Brushes": ["brush"],
  "Household::Buckets": ["bucket"],
  "Household::Cleaning Gloves": ["rubber gloves", "household gloves", "cleaning glove"],
  "Household::Cleaning Tools": ["cleaning tool"],
  "Household::Clothes Hangers": ["hanger", "coat hanger", "clothes hanger"],
  "Household::Clothespins": ["clothes pegs", "laundry clips", "clothespin"],
  "Household::Laundry Baskets": ["laundry basket", "hamper"],
  "Household::Ironing Supplies": ["ironing accessories", "ironing supply"],
  "Household::Shoe Care": ["shoe polish", "shoe cleaner"],
  "Household::Candles": ["candle"],
  "Household::Matches": ["match"],
  "Household::Lighters": ["lighter"],
  "Household::Emergency Supplies": ["emergency kit", "disaster supplies", "emergency supply"],

  // PERSONAL CARE
  "Personal Care::Soap": ["bath soap", "bar soap", "beauty bar"],
  "Personal Care::Body Wash": ["shower gel", "body gel"],
  "Personal Care::Shampoo": ["shampoo"],
  "Personal Care::Conditioner": ["conditioner"],
  "Personal Care::Hair Treatment": ["hair mask", "hair repair"],
  "Personal Care::Hair Color": ["hair dye"],
  "Personal Care::Hair Styling": ["styling gel", "hair styling products"],
  "Personal Care::Toothpaste": ["tooth paste", "dental paste"],
  "Personal Care::Toothbrush": ["tooth brush"],
  "Personal Care::Dental Floss": ["floss"],
  "Personal Care::Mouthwash": ["oral rinse"],
  "Personal Care::Feminine Care": ["feminine hygiene"],
  "Personal Care::Sanitary Napkins": ["sanitary pads", "menstrual pads", "sanitary napkin"],
  "Personal Care::Panty Liners": ["pantyliners", "liners", "panty liner"],
  "Personal Care::Tampons": ["tampon"],
  "Personal Care::Adult Diapers": ["adult nappies", "adult diaper"],
  "Personal Care::Baby Wipes": ["baby wet wipes", "baby wipe"],
  "Personal Care::Tissues": ["tissue paper", "tissue"],
  "Personal Care::Cotton Balls": ["cotton ball"],
  "Personal Care::Cotton Buds": ["cotton swabs", "q tips", "cotton bud"],
  "Personal Care::Rubbing Alcohol": ["isopropyl alcohol", "ethyl alcohol"],
  "Personal Care::Hand Sanitizer": ["sanitizer", "alcohol gel"],
  "Personal Care::Face Mask": ["facial mask"],
  "Personal Care::Disposable Gloves": ["single use gloves", "disposable glove"],
  "Personal Care::Deodorant": ["deo", "antiperspirant"],
  "Personal Care::Perfume": ["fragrance"],
  "Personal Care::Cologne": ["eau de cologne"],
  "Personal Care::Body Spray": ["body mist", "fragrance spray"],
  "Personal Care::Body Lotion": ["lotion"],
  "Personal Care::Body Cream": ["body moisturizer"],
  "Personal Care::Petroleum Jelly": ["petrolatum", "vaseline"],
  "Personal Care::Lip Balm": ["lip care"],
  "Personal Care::Hand Cream": ["hand lotion"],
  "Personal Care::Foot Care": ["foot cream", "foot treatment"],
  "Personal Care::Shaving Cream": ["shave cream"],
  "Personal Care::Razors": ["razor", "shaver"],
  "Personal Care::Aftershave": ["after shave"],
  "Personal Care::Nail Clippers": ["nail cutter", "nail clipper"],
  "Personal Care::Nail Care": ["manicure supplies"],
  "Personal Care::Combs": ["comb"],
  "Personal Care::Hair Brushes": ["hair brush"],
  "Personal Care::Hair Accessories": ["hair clips", "hair ties", "hair accessory"],
  "Personal Care::Bath Accessories": ["bathroom accessories", "shower accessories", "bath accessory"],
  "Personal Care::Travel Toiletries": ["travel size toiletries", "toiletry kit", "travel toiletry"],

  // BEAUTY & COSMETICS
  "Beauty & Cosmetics::Makeup": ["makeup"],
  "Beauty & Cosmetics::Foundation": ["foundation"],
  "Beauty & Cosmetics::BB Cream": ["blemish balm", "beauty balm"],
  "Beauty & Cosmetics::CC Cream": ["color correcting cream", "colour correcting cream"],
  "Beauty & Cosmetics::Concealer": ["concealer"],
  "Beauty & Cosmetics::Face Powder": ["facial powder"],
  "Beauty & Cosmetics::Pressed Powder": ["compact powder"],
  "Beauty & Cosmetics::Loose Powder": ["setting powder"],
  "Beauty & Cosmetics::Blush": ["blush"],
  "Beauty & Cosmetics::Bronzer": ["bronzer"],
  "Beauty & Cosmetics::Highlighter": ["highlighter"],
  "Beauty & Cosmetics::Contour": ["contour"],
  "Beauty & Cosmetics::Primer": ["primer"],
  "Beauty & Cosmetics::Setting Spray": ["makeup setting spray"],
  "Beauty & Cosmetics::Lipstick": ["lipstick"],
  "Beauty & Cosmetics::Lip Tint": ["lip stain"],
  "Beauty & Cosmetics::Lip Gloss": ["lipgloss"],
  "Beauty & Cosmetics::Lip Liner": ["lip liner"],
  "Beauty & Cosmetics::Mascara": ["mascara"],
  "Beauty & Cosmetics::Eyeliner": ["eyeliner"],
  "Beauty & Cosmetics::Eyebrow Pencil": ["brow pencil"],
  "Beauty & Cosmetics::Eyebrow Gel": ["brow gel"],
  "Beauty & Cosmetics::Eyeshadow": ["eyeshadow"],
  "Beauty & Cosmetics::False Eyelashes": ["fake lashes", "false lashes", "false eyelash"],
  "Beauty & Cosmetics::Eyelash Glue": ["lash glue"],
  "Beauty & Cosmetics::Makeup Remover": ["cosmetic remover"],
  "Beauty & Cosmetics::Micellar Water": ["micellar cleansing water"],
  "Beauty & Cosmetics::Facial Cleanser": ["face cleanser"],
  "Beauty & Cosmetics::Facial Wash": ["face wash"],
  "Beauty & Cosmetics::Face Toner": ["facial toner"],
  "Beauty & Cosmetics::Face Serum": ["facial serum"],
  "Beauty & Cosmetics::Face Cream": ["facial cream"],
  "Beauty & Cosmetics::Moisturizer": ["moisturiser"],
  "Beauty & Cosmetics::Sunscreen": ["sun screen", "spf lotion"],
  "Beauty & Cosmetics::Sunblock": ["sun block"],
  "Beauty & Cosmetics::Exfoliator": ["exfoliator"],
  "Beauty & Cosmetics::Facial Scrub": ["face scrub"],
  "Beauty & Cosmetics::Acne Treatment": ["pimple treatment"],
  "Beauty & Cosmetics::Anti-Aging": ["anti aging", "anti wrinkle"],
  "Beauty & Cosmetics::Beauty Tools": ["cosmetic tools", "beauty tool"],
  "Beauty & Cosmetics::Makeup Brushes": ["cosmetic brushes", "makeup brush"],
  "Beauty & Cosmetics::Beauty Sponges": ["makeup sponge", "blending sponge", "beauty sponge"],
  "Beauty & Cosmetics::Cotton Pads": ["cotton pad"],
  "Beauty & Cosmetics::Nail Polish": ["nail color", "nail varnish"],
  "Beauty & Cosmetics::Nail Polish Remover": ["acetone", "nail remover"],
  "Beauty & Cosmetics::Artificial Nails": ["fake nails", "press on nails", "artificial nail"],
  "Beauty & Cosmetics::Cuticle Care": ["cuticle remover", "cuticle oil"],
  "Beauty & Cosmetics::Body Mist": ["body spray"],

  // BABY CARE
  "Baby Care::Baby Formula": ["infant formula", "formula milk"],
  "Baby Care::Baby Cereal": ["infant cereal"],
  "Baby Care::Baby Snacks": ["toddler snacks", "baby snack"],
  "Baby Care::Baby Bottles": ["feeding bottles", "baby bottle"],
  "Baby Care::Bottle Nipples": ["bottle teats", "feeding nipples", "bottle nipple"],
  "Baby Care::Bottle Cleaners": ["bottle cleaning brush", "bottle cleaner"],
  "Baby Care::Bottle Sterilizers": ["bottle steriliser", "bottle sterilizer"],
  "Baby Care::Baby Diapers": ["baby nappies", "baby diaper"],
  "Baby Care::Training Pants": ["pull ups", "training diapers", "training pant"],
  "Baby Care::Baby Powder": ["infant powder"],
  "Baby Care::Baby Lotion": ["infant lotion"],
  "Baby Care::Baby Shampoo": ["infant shampoo"],
  "Baby Care::Baby Soap": ["infant soap"],
  "Baby Care::Baby Wash": ["baby body wash"],
  "Baby Care::Baby Oil": ["infant oil"],
  "Baby Care::Baby Cream": ["baby cream"],
  "Baby Care::Diaper Rash Cream": ["nappy rash cream"],
  "Baby Care::Pacifiers": ["pacifier", "dummy"],
  "Baby Care::Teethers": ["teething toy", "teether"],
  "Baby Care::Baby Utensils": ["baby cutlery", "baby utensil"],
  "Baby Care::Baby Bibs": ["bib", "baby bib"],
  "Baby Care::Baby Clothing": ["baby clothing"],
  "Baby Care::Baby Blankets": ["infant blanket", "baby blanket"],
  "Baby Care::Baby Towels": ["infant towel", "baby towel"],
  "Baby Care::Baby Bath Accessories": ["baby bathing accessories", "baby bath accessory"],
  "Baby Care::Baby Toys": ["baby toy"],
  "Baby Care::Baby Safety": ["childproofing", "baby proofing"],
  "Baby Care::Baby Feeding Accessories": ["feeding accessories", "baby feeding accessory"],

  // MEDICINE & HEALTH
  "Medicine & Health::Pain Relief": ["pain reliever", "painkiller", "paracetamol", "ibuprofen"],
  "Medicine & Health::Fever Medicine": ["fever reducer", "antipyretic"],
  "Medicine & Health::Cold Medicine": ["cold meds", "decongestant"],
  "Medicine & Health::Cough Medicine": ["cough syrup", "cough remedy"],
  "Medicine & Health::Flu Medicine": ["influenza medicine"],
  "Medicine & Health::Allergy Medicine": ["antihistamine", "allergy relief"],
  "Medicine & Health::Antibiotics": ["antibiotic"],
  "Medicine & Health::Antifungal": ["antifungal medicine"],
  "Medicine & Health::Antiviral": ["antiviral medicine"],
  "Medicine & Health::Antiseptics": ["antiseptic", "wound disinfectant"],
  "Medicine & Health::Vitamins": ["vitamin"],
  "Medicine & Health::Multivitamins": ["multivitamin"],
  "Medicine & Health::Vitamin C": ["ascorbic acid"],
  "Medicine & Health::Vitamin D": ["cholecalciferol"],
  "Medicine & Health::Calcium": ["calcium"],
  "Medicine & Health::Iron Supplements": ["iron supplement", "ferrous sulfate"],
  "Medicine & Health::Fish Oil": ["omega 3", "omega-3"],
  "Medicine & Health::Herbal Supplements": ["herbal supplement"],
  "Medicine & Health::Digestive Health": ["digestive aid"],
  "Medicine & Health::Probiotics": ["probiotic"],
  "Medicine & Health::Antacids": ["antacid", "acid relief"],
  "Medicine & Health::Diarrhea Medicine": ["anti diarrhea", "antidiarrheal"],
  "Medicine & Health::Laxatives": ["laxative"],
  "Medicine & Health::Medical Supplies": ["medical equipment", "health supplies", "medical supply"],
  "Medicine & Health::Bandages": ["bandage", "band aid", "band-aid"],
  "Medicine & Health::Gauze": ["gauze pad", "sterile gauze"],
  "Medicine & Health::Medical Tape": ["surgical tape"],
  "Medicine & Health::Cotton": ["cotton"],
  "Medicine & Health::Hydrogen Peroxide": ["peroxide"],
  "Medicine & Health::Betadine": ["povidone iodine", "povidone-iodine"],
  "Medicine & Health::Thermometers": ["thermometer"],
  "Medicine & Health::Blood Pressure Monitors": ["bp monitor", "sphygmomanometer", "blood pressure monitor"],
  "Medicine & Health::Blood Sugar Monitors": ["glucose meter", "glucometer", "blood sugar monitor"],
  "Medicine & Health::Nebulizers": ["nebulizer"],
  "Medicine & Health::Face Masks": ["face mask", "medical mask"],
  "Medicine & Health::Medical Gloves": ["examination gloves", "surgical gloves", "medical glove"],
  "Medicine & Health::First Aid Kits": ["first aid kit"],
  "Medicine & Health::Prescription Medicine": ["prescription drugs", "rx medicine"],
  "Medicine & Health::Over-the-Counter Medicine": ["over the counter medicine", "otc medicine"],
  "Medicine & Health::Eye Drops": ["eyedrops", "eye drop"],
  "Medicine & Health::Ear Drops": ["eardrops", "ear drop"],
  "Medicine & Health::Nasal Spray": ["nose spray"],

  // SCHOOL & OFFICE SUPPLIES
  "School & Office Supplies::Notebooks": ["notebook"],
  "School & Office Supplies::Writing Pads": ["writing pad", "pad paper"],
  "School & Office Supplies::Loose Leaf Paper": ["looseleaf paper", "loose leaf"],
  "School & Office Supplies::Bond Paper": ["copy paper"],
  "School & Office Supplies::Colored Paper": ["colour paper", "construction paper"],
  "School & Office Supplies::Index Cards": ["index card"],
  "School & Office Supplies::Pens": ["pen", "ballpen", "ballpoint pen"],
  "School & Office Supplies::Ballpens": ["ballpen", "ball point pen"],
  "School & Office Supplies::Gel Pens": ["gel pen"],
  "School & Office Supplies::Markers": ["marker"],
  "School & Office Supplies::Highlighters": ["highlighter"],
  "School & Office Supplies::Pencils": ["pencil"],
  "School & Office Supplies::Mechanical Pencils": ["mechanical pencil"],
  "School & Office Supplies::Colored Pencils": ["colour pencils", "coloring pencils", "colored pencil"],
  "School & Office Supplies::Crayons": ["crayon"],
  "School & Office Supplies::Oil Pastels": ["oil pastel"],
  "School & Office Supplies::Watercolors": ["watercolor", "watercolour"],
  "School & Office Supplies::Paint": ["paint"],
  "School & Office Supplies::Paint Brushes": ["paint brush"],
  "School & Office Supplies::Erasers": ["eraser"],
  "School & Office Supplies::Sharpeners": ["pencil sharpener", "sharpener"],
  "School & Office Supplies::Correction Tape": ["white out tape"],
  "School & Office Supplies::Correction Fluid": ["white out", "correction liquid"],
  "School & Office Supplies::Glue": ["adhesive glue", "school glue"],
  "School & Office Supplies::Glue Sticks": ["glue stick"],
  "School & Office Supplies::Scissors": ["scissor"],
  "School & Office Supplies::Rulers": ["ruler"],
  "School & Office Supplies::Protractors": ["protractor"],
  "School & Office Supplies::Compasses": ["drawing compass", "compass"],
  "School & Office Supplies::Staplers": ["stapler"],
  "School & Office Supplies::Staples": ["staple wire", "staple"],
  "School & Office Supplies::Paper Clips": ["paperclip", "paper clip"],
  "School & Office Supplies::Binder Clips": ["binder clip"],
  "School & Office Supplies::Folders": ["folder"],
  "School & Office Supplies::Envelopes": ["envelope"],
  "School & Office Supplies::Binders": ["ring binder", "binder"],
  "School & Office Supplies::Document Holders": ["document case", "file holder", "document holder"],
  "School & Office Supplies::Whiteboards": ["whiteboard"],
  "School & Office Supplies::Whiteboard Markers": ["board marker", "dry erase marker", "whiteboard marker"],
  "School & Office Supplies::Chalk": ["chalk"],
  "School & Office Supplies::Calculators": ["calculator"],
  "School & Office Supplies::Desk Organizers": ["desk organizer"],
  "School & Office Supplies::Sticky Notes": ["sticky note", "post it", "post-it"],
  "School & Office Supplies::Labels": ["label stickers", "stickers", "label"],
  "School & Office Supplies::Printer Ink": ["ink cartridge"],
  "School & Office Supplies::Printer Toner": ["toner cartridge"],
  "School & Office Supplies::Printer Paper": ["printing paper"],
  "School & Office Supplies::Laminating Supplies": ["lamination supplies", "laminating supply"],
  "School & Office Supplies::Office Chairs": ["office chair"],
  "School & Office Supplies::Office Accessories": ["office accessory"],
  "School & Office Supplies::School Bags": ["school bag"],
  "School & Office Supplies::Backpacks": ["backpack"],
  "School & Office Supplies::Lunch Boxes": ["lunch box", "lunchbox"],
  "School & Office Supplies::Water Bottles": ["water bottle"],

  // HARDWARE
  "Hardware::Hand Tools": ["manual tools", "hand tool"],
  "Hardware::Power Tools": ["electric tools", "cordless tools", "power tool"],
  "Hardware::Tool Sets": ["tool kit", "toolset", "tool set"],
  "Hardware::Tool Storage": ["tool box", "toolbox"],
  "Hardware::Hammers": ["hammer"],
  "Hardware::Screwdrivers": ["screwdriver"],
  "Hardware::Wrenches": ["wrench", "spanner"],
  "Hardware::Pliers": ["plier"],
  "Hardware::Sockets": ["socket wrench", "socket"],
  "Hardware::Allen Keys": ["hex keys", "hex wrench", "allen key"],
  "Hardware::Tape Measures": ["tape measure", "measuring tape"],
  "Hardware::Levels": ["spirit level", "level"],
  "Hardware::Utility Knives": ["utility knife", "box cutter", "cutter"],
  "Hardware::Hand Saws": ["hand saw"],
  "Hardware::Chisels": ["chisel"],
  "Hardware::Files": ["file"],
  "Hardware::Clamps": ["clamp"],
  "Hardware::Vises": ["vise"],
  "Hardware::Drill Bits": ["drill bit"],
  "Hardware::Saw Blades": ["saw blade"],
  "Hardware::Grinding Discs": ["grinding disc"],
  "Hardware::Sandpaper": ["abrasive paper"],
  "Hardware::Wire Brushes": ["wire brush"],
  "Hardware::Nails": ["nail"],
  "Hardware::Concrete Nails": ["masonry nails", "concrete nail"],
  "Hardware::Finishing Nails": ["finish nails", "finishing nail"],
  "Hardware::Roofing Nails": ["roof nails", "roofing nail"],
  "Hardware::Screws": ["screw"],
  "Hardware::Wood Screws": ["timber screws", "wood screw"],
  "Hardware::Machine Screws": ["machine screw"],
  "Hardware::Self-Tapping Screws": ["self tapping screws", "self-tapping screw"],
  "Hardware::Drywall Screws": ["gypsum screws", "drywall screw"],
  "Hardware::Bolts & Nuts": ["bolts and nuts", "nuts and bolts", "bolts & nut"],
  "Hardware::Washers": ["washer"],
  "Hardware::Anchors": ["anchor"],
  "Hardware::Wall Plugs": ["rawl plugs", "plastic anchors", "wall plug"],
  "Hardware::Rivets": ["rivet"],
  "Hardware::Fasteners": ["fastener"],
  "Hardware::Chains": ["chain"],
  "Hardware::Hooks": ["hook"],
  "Hardware::Eye Bolts": ["eye bolt"],
  "Hardware::Turnbuckles": ["turnbuckle"],
  "Hardware::Cable Ties": ["zip ties", "tie wraps", "cable tie"],
  "Hardware::Ropes": ["rope"],
  "Hardware::Steel Wires": ["steel wire"],
  "Hardware::Adhesives": ["adhesive"],
  "Hardware::Super Glue": ["instant glue", "cyanoacrylate"],
  "Hardware::Epoxy": ["epoxy adhesive", "epoxy glue"],
  "Hardware::Wood Glue": ["carpenter glue"],
  "Hardware::Construction Adhesive": ["building adhesive"],
  "Hardware::Sealants": ["sealant"],
  "Hardware::Silicone Sealant": ["silicone", "silicon sealant"],
  "Hardware::Caulking": ["caulk"],
  "Hardware::Thread Seal Tape": ["teflon tape", "ptfe tape"],
  "Hardware::Wood Stain": ["wood color"],
  "Hardware::Varnish": ["varnish"],
  "Hardware::Paint Thinner": ["thinner"],
  "Hardware::Paint Remover": ["paint stripper"],
  "Hardware::Painting Supplies": ["painting tools", "painting supply"],
  "Hardware::Paint Rollers": ["paint roller"],
  "Hardware::Paint Trays": ["paint tray"],
  "Hardware::Masking Tape": ["painter tape"],
  "Hardware::Drop Cloths": ["drop cloth"],
  "Hardware::Electrical Supplies": ["electrical materials", "electrical supply"],
  "Hardware::Electrical Wires": ["electric wire", "electrical wire"],
  "Hardware::Electrical Cables": ["electric cable", "electrical cable"],
  "Hardware::Extension Cords": ["extension cord", "extension wire"],
  "Hardware::Electrical Tape": ["insulation tape"],
  "Hardware::Circuit Breakers": ["circuit breaker", "breaker"],
  "Hardware::Fuses": ["fuse"],
  "Hardware::Wall Switches": ["light switches", "wall switch"],
  "Hardware::Electrical Outlets": ["power outlets", "wall sockets", "electrical outlet"],
  "Hardware::Light Bulbs": ["light bulb"],
  "Hardware::LED Bulbs": ["led light bulb", "led bulb", "light emitting diode bulbs"],
  "Hardware::Lamp Holders": ["bulb holder", "lamp holder"],
  "Hardware::Junction Boxes": ["junction box"],
  "Hardware::Conduits": ["conduit"],
  "Hardware::Plumbing Supplies": ["plumbing materials", "plumbing supply"],
  "Hardware::PVC Pipes & Fittings": ["pvc pipes and fittings", "pvc plumbing", "pvc pipes & fitting", "polyvinyl chloride pipes & fittings"],
  "Hardware::PPR Pipes & Fittings": ["ppr pipes and fittings", "ppr pipes & fitting", "polypropylene random pipes & fittings"],
  "Hardware::GI Pipes": ["galvanized iron pipes", "galvanised iron pipes", "gi pipe"],
  "Hardware::Pipe Clamps": ["pipe clip", "pipe clamp"],
  "Hardware::Pipe Sealants": ["pipe sealant"],
  "Hardware::Pipe Insulation": ["pipe lagging"],
  "Hardware::Faucets": ["faucet"],
  "Hardware::Shower Heads": ["showerhead", "shower head"],
  "Hardware::Water Hoses": ["water hose"],
  "Hardware::Garden Hoses": ["garden hose"],
  "Hardware::Hose Connectors": ["hose fitting", "hose connector"],
  "Hardware::Valves": ["valve"],
  "Hardware::Water Pumps": ["water pump"],
  "Hardware::Construction Materials": ["building materials", "construction material"],
  "Hardware::Cement": ["cement"],
  "Hardware::Concrete Mix": ["ready mix concrete"],
  "Hardware::Sand": ["sand"],
  "Hardware::Gravel": ["gravel"],
  "Hardware::Bricks": ["brick"],
  "Hardware::Hollow Blocks": ["concrete hollow blocks", "chb", "hollow block"],
  "Hardware::Roofing Sheets": ["roof sheets", "roofing sheet"],
  "Hardware::Metal Sheets": ["sheet metal", "metal sheet"],
  "Hardware::Steel Bars": ["rebar", "reinforcing bars", "steel bar"],
  "Hardware::Plywood": ["plywood"],
  "Hardware::Lumber": ["lumber"],
  "Hardware::Insulation Materials": ["insulation", "insulation material"],
  "Hardware::Roof Sealants": ["roof sealant"],
  "Hardware::Safety Equipment": ["safety gear", "ppe"],
  "Hardware::Hard Hats": ["hard hat", "safety helmet"],
  "Hardware::Safety Glasses": ["safety goggles", "safety glass"],
  "Hardware::Face Shields": ["face shield"],
  "Hardware::Ear Protection": ["earmuffs", "ear plugs"],
  "Hardware::Work Gloves": ["working gloves", "work glove"],
  "Hardware::Safety Shoes": ["work boots", "safety boots", "safety shoe"],
  "Hardware::Safety Harnesses": ["safety harness"],
  "Hardware::Reflective Vests": ["safety vest", "reflectorized vest", "reflective vest"],
  "Hardware::Respirators": ["respirator"],
  "Hardware::Dust Masks": ["dust mask"],
  "Hardware::Fire Extinguishers": ["fire extinguisher"],
  "Hardware::Locks": ["lock"],
  "Hardware::Padlocks": ["padlock"],
  "Hardware::Door Locks": ["door lock"],
  "Hardware::Deadbolts": ["deadbolt"],
  "Hardware::Combination Locks": ["combination lock"],
  "Hardware::Smart Locks": ["smart lock"],
  "Hardware::Keys": ["key"],
  "Hardware::Hinges": ["hinge"],
  "Hardware::Door Closers": ["door closer"],
  "Hardware::Drawer Slides": ["drawer runners", "drawer slide"],
  "Hardware::Cabinet Handles": ["cabinet pulls", "cabinet handle"],
  "Hardware::Cabinet Knobs": ["cabinet knob"],
  "Hardware::Furniture Casters": ["caster wheels", "furniture caster"],
  "Hardware::Gardening Tools": ["garden tools", "gardening tool"],
  "Hardware::Shovels": ["shovel"],
  "Hardware::Spades": ["spade"],
  "Hardware::Rakes": ["rake"],
  "Hardware::Garden Hoes": ["garden hoe"],
  "Hardware::Pruning Shears": ["pruner", "secateurs", "pruning shear"],
  "Hardware::Grass Cutters": ["brush cutter", "grass trimmer", "grass cutter"],
  "Hardware::Wheelbarrows": ["wheelbarrow"],
  "Hardware::Sprayers": ["sprayer"],
  "Hardware::Watering Cans": ["watering can"],

  // HOME IMPROVEMENT
  "Home Improvement::Flooring": ["flooring"],
  "Home Improvement::Tiles": ["tile"],
  "Home Improvement::Vinyl Flooring": ["vinyl floor"],
  "Home Improvement::Laminate Flooring": ["laminated flooring"],
  "Home Improvement::Wood Flooring": ["wooden flooring"],
  "Home Improvement::Carpets": ["carpet"],
  "Home Improvement::Wallpaper": ["wallpaper"],
  "Home Improvement::Wall Panels": ["wall panel"],
  "Home Improvement::Ceiling Panels": ["ceiling panel"],
  "Home Improvement::Roofing Materials": ["roof materials", "roofing material"],
  "Home Improvement::Doors": ["door"],
  "Home Improvement::Windows": ["window"],
  "Home Improvement::Window Blinds": ["blinds", "window blind"],
  "Home Improvement::Curtain Rods": ["curtain pole", "curtain rod"],
  "Home Improvement::Curtains": ["curtain"],
  "Home Improvement::Cabinets": ["cabinet"],
  "Home Improvement::Kitchen Cabinets": ["kitchen cabinet"],
  "Home Improvement::Bathroom Fixtures": ["bath fixtures", "bathroom fixture"],
  "Home Improvement::Sinks": ["sink"],
  "Home Improvement::Toilets": ["toilet"],
  "Home Improvement::Bathtubs": ["bathtub"],
  "Home Improvement::Bathroom Accessories": ["bathroom fittings", "bathroom accessory"],
  "Home Improvement::Mirrors": ["mirror"],
  "Home Improvement::Shelves": ["shelf"],
  "Home Improvement::Storage Cabinets": ["storage cabinet"],
  "Home Improvement::Furniture Hardware": ["furniture fittings"],
  "Home Improvement::Home Security": ["house security"],
  "Home Improvement::Door Bells": ["doorbell", "door bell"],
  "Home Improvement::CCTV Accessories": ["security camera accessories", "cctv accessory", "closed circuit television accessories"],
  "Home Improvement::Smoke Detectors": ["smoke alarm", "smoke detector"],
  "Home Improvement::Carbon Monoxide Detectors": ["co detector", "carbon monoxide alarm", "carbon monoxide detector"],
  "Home Improvement::Home Automation": ["smart home"],
  "Home Improvement::Smart Lighting": ["smart lights"],
  "Home Improvement::Smart Plugs": ["wifi plugs", "wi-fi plugs", "smart plug"],
  "Home Improvement::Smart Sensors": ["smart home sensors", "smart sensor"],

  // ELECTRONICS
  "Electronics::Mobile Phones": ["cellphones", "cell phones", "phones", "mobile phone"],
  "Electronics::Smartphones": ["smart phones", "mobile phone", "smartphone"],
  "Electronics::Feature Phones": ["basic phones", "keypad phones", "feature phone"],
  "Electronics::Tablets": ["tablet"],
  "Electronics::Laptops": ["laptop"],
  "Electronics::Desktop Computers": ["desktop pc", "computer", "desktop computer"],
  "Electronics::Computer Monitors": ["pc monitor", "display monitor", "computer monitor"],
  "Electronics::Mini PCs": ["mini pc"],
  "Electronics::Keyboards": ["keyboard"],
  "Electronics::Mechanical Keyboards": ["mechanical keyboard"],
  "Electronics::Mice": ["mouse"],
  "Electronics::Mouse Pads": ["mouse mat", "mouse pad"],
  "Electronics::Webcams": ["webcam"],
  "Electronics::Microphones": ["microphone"],
  "Electronics::Headphones": ["headphone"],
  "Electronics::Earphones": ["earphone"],
  "Electronics::Wireless Earbuds": ["true wireless earbuds", "tws earbuds", "wireless earbud"],
  "Electronics::Speakers": ["speaker"],
  "Electronics::Bluetooth Speakers": ["wireless speakers", "bluetooth speaker"],
  "Electronics::Power Banks": ["powerbank", "portable charger", "power bank"],
  "Electronics::Chargers": ["charger", "charging adapter", "wall charger"],
  "Electronics::Charging Cables": ["charger cable", "phone cable", "charging cable"],
  "Electronics::USB Cables": ["usb cable", "universal serial bus cable", "universal serial bus cables"],
  "Electronics::Lightning Cables": ["iphone cable", "lightning cable"],
  "Electronics::USB Hubs": ["usb hub", "universal serial bus hubs"],
  "Electronics::Adapters": ["adapter"],
  "Electronics::Power Adapters": ["power adapter", "ac adapter"],
  "Electronics::Extension Outlets": ["power strip", "extension socket", "extension outlet"],
  "Electronics::Surge Protectors": ["surge protector", "surge suppressor"],
  "Electronics::Memory Cards": ["memory card", "sd card", "microsd card"],
  "Electronics::USB Flash Drives": ["flash drive", "thumb drive", "usb drive", "usb flash drive", "universal serial bus flash drives"],
  "Electronics::External Hard Drives": ["external hard drive", "external hdd"],
  "Electronics::SSDs": ["ssd", "solid state drive", "solid state drives"],
  "Electronics::Computer Components": ["pc components", "computer parts", "computer component"],
  "Electronics::Processors": ["processor"],
  "Electronics::Motherboards": ["motherboard"],
  "Electronics::Graphics Cards": ["graphics card", "gpu", "video card"],
  "Electronics::RAM": ["memory module", "computer memory"],
  "Electronics::Power Supplies": ["power supply", "psu"],
  "Electronics::Computer Cases": ["pc case", "computer chassis", "computer case"],
  "Electronics::Cooling Fans": ["pc fan", "case fan", "cooling fan"],
  "Electronics::Thermal Paste": ["thermal compound"],
  "Electronics::Networking Devices": ["network equipment", "networking device"],
  "Electronics::Wi-Fi Routers": ["wifi router", "wireless router", "wi fi routers", "wi-fi router"],
  "Electronics::Wi-Fi Extenders": ["wifi extender", "wireless repeater", "wi fi extenders", "wi-fi extender"],
  "Electronics::Network Switches": ["network switch", "ethernet switch"],
  "Electronics::Modems": ["modem"],
  "Electronics::LAN Cables": ["ethernet cable", "network cable", "lan cable", "local area network cables"],
  "Electronics::HDMI Cables": ["hdmi cable", "high definition multimedia interface cables"],
  "Electronics::DisplayPort Cables": ["displayport cable", "dp cable"],
  "Electronics::Televisions": ["television"],
  "Electronics::TV Boxes": ["android tv box", "set top box", "tv box"],
  "Electronics::Streaming Devices": ["media streamer", "streaming device"],
  "Electronics::Projectors": ["projector"],
  "Electronics::Printers": ["printer"],
  "Electronics::Scanners": ["scanner"],
  "Electronics::Printer Accessories": ["printer supplies", "printer accessory"],
  "Electronics::Security Cameras": ["cctv camera", "surveillance camera", "security camera"],
  "Electronics::CCTV Systems": ["security camera system", "surveillance system", "cctv system", "closed circuit television systems"],
  "Electronics::Smart Watches": ["smartwatch", "smart watch"],
  "Electronics::Fitness Trackers": ["activity tracker", "fitness tracker"],
  "Electronics::Drones": ["drone"],
  "Electronics::VR Headsets": ["virtual reality headset", "vr headset", "virtual reality headsets"],
  "Electronics::Electronic Components": ["electronic parts", "electronic component"],
  "Electronics::Breadboards": ["breadboard"],
  "Electronics::Resistors": ["resistor"],
  "Electronics::Capacitors": ["capacitor"],
  "Electronics::Transistors": ["transistor"],
  "Electronics::Microcontrollers": ["microcontroller"],
  "Electronics::Arduino Boards": ["arduino board"],
  "Electronics::ESP32 Boards": ["esp32 board", "esp32"],
  "Electronics::Raspberry Pi": ["raspberry pi board", "rpi"],
  "Electronics::Sensors": ["sensor"],
  "Electronics::Relays": ["relay"],
  "Electronics::Servo Motors": ["servo motor", "servo"],
  "Electronics::Stepper Motors": ["stepper motor"],
  "Electronics::LCD Displays": ["lcd display", "lcd screen", "liquid crystal display displays"],
  "Electronics::OLED Displays": ["oled display", "oled screen", "organic led displays"],

  // APPLIANCES
  "Appliances::Refrigerators": ["refrigerator"],
  "Appliances::Freezers": ["freezer"],
  "Appliances::Air Conditioners": ["aircon", "air conditioner", "ac unit"],
  "Appliances::Electric Fans": ["electric fan"],
  "Appliances::Stand Fans": ["pedestal fan", "standing fan", "stand fan"],
  "Appliances::Desk Fans": ["table fan", "desk fan"],
  "Appliances::Ceiling Fans": ["ceiling fan"],
  "Appliances::Exhaust Fans": ["ventilation fan", "exhaust fan"],
  "Appliances::Washing Machines": ["washing machine", "washer"],
  "Appliances::Dryers": ["dryer"],
  "Appliances::Clothes Drying Cabinets": ["drying cabinet", "clothes drying cabinet"],
  "Appliances::Microwave Ovens": ["microwave", "microwave oven"],
  "Appliances::Electric Ovens": ["electric oven"],
  "Appliances::Toaster Ovens": ["oven toaster", "toaster oven"],
  "Appliances::Rice Cookers": ["rice cooker"],
  "Appliances::Pressure Cookers": ["pressure cooker"],
  "Appliances::Slow Cookers": ["slow cooker", "crock pot"],
  "Appliances::Multi Cookers": ["multicooker", "multi cooker"],
  "Appliances::Induction Cookers": ["induction stove", "induction cooker"],
  "Appliances::Electric Stoves": ["electric stove"],
  "Appliances::Gas Stoves": ["gas range", "gas cooker", "gas stove"],
  "Appliances::Range Hoods": ["kitchen hood", "cooker hood", "range hood"],
  "Appliances::Coffee Makers": ["coffee machine", "coffee maker"],
  "Appliances::Espresso Machines": ["espresso maker", "espresso machine"],
  "Appliances::Electric Kettles": ["electric kettle"],
  "Appliances::Water Dispensers": ["water dispenser"],
  "Appliances::Water Purifiers": ["water filter", "water purifier"],
  "Appliances::Blenders": ["blender"],
  "Appliances::Food Processors": ["food processor"],
  "Appliances::Mixers": ["mixer"],
  "Appliances::Juicers": ["juicer"],
  "Appliances::Air Fryers": ["air fryer"],
  "Appliances::Deep Fryers": ["deep fryer"],
  "Appliances::Sandwich Makers": ["sandwich toaster", "sandwich maker"],
  "Appliances::Waffle Makers": ["waffle iron", "waffle maker"],
  "Appliances::Bread Makers": ["bread machine", "bread maker"],
  "Appliances::Ice Makers": ["ice machine", "ice maker"],
  "Appliances::Vacuum Cleaners": ["vacuum", "vacuum cleaner"],
  "Appliances::Robot Vacuums": ["robot vacuum", "robotic vacuum"],
  "Appliances::Steam Cleaners": ["steam cleaner"],
  "Appliances::Garment Steamers": ["clothes steamer", "garment steamer"],
  "Appliances::Irons": ["iron"],
  "Appliances::Hair Dryers": ["hair dryer", "blow dryer"],
  "Appliances::Hair Straighteners": ["flat iron", "hair iron", "hair straightener"],
  "Appliances::Curling Irons": ["hair curler", "curling iron"],
  "Appliances::Dehumidifiers": ["dehumidifier"],
  "Appliances::Humidifiers": ["humidifier"],
  "Appliances::Air Purifiers": ["air purifier"],
  "Appliances::Electric Heaters": ["space heater", "electric heater"],
  "Appliances::Water Heaters": ["water heater"],
  "Appliances::Sewing Machines": ["sewing machine"],

  // AUTOMOTIVE
  "Automotive::Engine Oil": ["motor oil"],
  "Automotive::Transmission Fluid": ["atf", "gearbox fluid"],
  "Automotive::Brake Fluid": ["brake oil"],
  "Automotive::Coolant": ["coolant"],
  "Automotive::Radiator Fluid": ["radiator coolant"],
  "Automotive::Power Steering Fluid": ["steering fluid"],
  "Automotive::Gear Oil": ["gear lubricant"],
  "Automotive::Fuel Additives": ["fuel treatment", "fuel additive"],
  "Automotive::Engine Additives": ["engine treatment", "engine additive"],
  "Automotive::Grease": ["grease"],
  "Automotive::Lubricants": ["lubricant"],
  "Automotive::Car Batteries": ["automotive battery", "car battery"],
  "Automotive::Battery Chargers": ["battery charger"],
  "Automotive::Battery Terminals": ["battery connector", "battery terminal"],
  "Automotive::Battery Accessories": ["battery accessory"],
  "Automotive::Spark Plugs": ["spark plug"],
  "Automotive::Ignition Coils": ["ignition coil"],
  "Automotive::Air Filters": ["air filter"],
  "Automotive::Oil Filters": ["oil filter"],
  "Automotive::Fuel Filters": ["fuel filter"],
  "Automotive::Cabin Filters": ["cabin air filter", "cabin filter"],
  "Automotive::Windshield Wipers": ["windscreen wipers", "windshield wiper"],
  "Automotive::Wiper Blades": ["wiper blade"],
  "Automotive::Headlights": ["headlight"],
  "Automotive::Fog Lights": ["fog lamps", "fog light"],
  "Automotive::Tail Lights": ["taillights", "rear lights", "tail light"],
  "Automotive::Signal Lights": ["turn signals", "indicator lights", "signal light"],
  "Automotive::Automotive Bulbs": ["car bulbs", "automotive bulb"],
  "Automotive::Car Fuses": ["automotive fuses", "car fuse"],
  "Automotive::Tires": ["tire"],
  "Automotive::Inner Tubes": ["tire tubes", "tyre tubes", "inner tube"],
  "Automotive::Wheel Rims": ["car rims", "wheel rim"],
  "Automotive::Wheel Covers": ["hubcaps", "wheel cover"],
  "Automotive::Tire Repair Kits": ["tyre repair kit", "tire repair kit"],
  "Automotive::Air Compressors": ["air compressor", "tire inflator"],
  "Automotive::Jacks": ["jack"],
  "Automotive::Jack Stands": ["jack stand"],
  "Automotive::Jumper Cables": ["booster cables", "jumper cable"],
  "Automotive::Tow Ropes": ["towing rope", "tow rope"],
  "Automotive::Emergency Kits": ["car emergency kit", "emergency kit"],
  "Automotive::Car Tools": ["automotive tools", "car tool"],
  "Automotive::Seat Covers": ["car seat covers", "seat cover"],
  "Automotive::Floor Mats": ["car mats", "floor mat"],
  "Automotive::Steering Wheel Covers": ["steering cover", "steering wheel cover"],
  "Automotive::Car Organizers": ["car organizer"],
  "Automotive::Dash Cameras": ["dashcam", "dashboard camera", "dash camera"],
  "Automotive::Phone Holders": ["phone mount", "mobile holder", "phone holder"],
  "Automotive::Car Chargers": ["vehicle charger", "car charger"],
  "Automotive::Car Audio": ["car stereo"],
  "Automotive::Amplifiers": ["amplifier"],
  "Automotive::Subwoofers": ["subwoofer"],
  "Automotive::Cleaning Supplies": ["cleaning supply"],
  "Automotive::Car Shampoo": ["car shampoo"],
  "Automotive::Wax": ["wax"],
  "Automotive::Polish": ["polish"],
  "Automotive::Microfiber Cloths": ["microfibre cloth", "microfiber towel", "microfiber cloth"],
  "Automotive::Glass Cleaners": ["glass cleaner"],
  "Automotive::Pressure Washers": ["pressure washer"],
  "Automotive::Motorcycle Parts": ["motorbike parts", "motorcycle part"],
  "Automotive::Motorcycle Helmets": ["motorbike helmet", "motorcycle helmet"],
  "Automotive::Motorcycle Accessories": ["motorbike accessories", "motorcycle accessory"],

  // PET SUPPLIES
  "Pet Supplies::Dog Food": ["dog kibble", "canine food"],
  "Pet Supplies::Cat Food": ["cat kibble", "feline food"],
  "Pet Supplies::Fish Food": ["aquarium food", "fish feed"],
  "Pet Supplies::Bird Food": ["bird seed", "bird feed"],
  "Pet Supplies::Rabbit Food": ["rabbit feed"],
  "Pet Supplies::Hamster Food": ["hamster feed"],
  "Pet Supplies::Pet Treats": ["dog treats", "cat treats", "pet treat"],
  "Pet Supplies::Pet Vitamins": ["animal vitamins", "pet vitamin"],
  "Pet Supplies::Pet Supplements": ["animal supplements", "pet supplement"],
  "Pet Supplies::Pet Medicine": ["veterinary medicine", "animal medicine"],
  "Pet Supplies::Pet Shampoo": ["dog shampoo", "cat shampoo"],
  "Pet Supplies::Pet Conditioner": ["dog conditioner", "cat conditioner"],
  "Pet Supplies::Pet Soap": ["dog soap", "cat soap"],
  "Pet Supplies::Pet Wipes": ["animal wipes", "pet wipe"],
  "Pet Supplies::Pet Grooming": ["animal grooming"],
  "Pet Supplies::Pet Brushes": ["dog brush", "cat brush", "pet brush"],
  "Pet Supplies::Pet Nail Clippers": ["pet nail cutter", "pet nail clipper"],
  "Pet Supplies::Pet Toothpaste": ["dog toothpaste", "cat toothpaste"],
  "Pet Supplies::Pet Toothbrush": ["dog toothbrush", "cat toothbrush"],
  "Pet Supplies::Pet Collars": ["dog collar"],
  "Pet Supplies::Pet Leashes": ["dog leash", "dog lead", "cat leash", "cat lead"],
  "Pet Supplies::Pet Harnesses": ["dog harness", "cat harness", "pet harness"],
  "Pet Supplies::Pet Clothing": ["pet clothing"],
  "Pet Supplies::Pet Beds": ["dog bed", "cat bed", "pet bed"],
  "Pet Supplies::Pet Blankets": ["animal blanket", "pet blanket"],
  "Pet Supplies::Pet Toys": ["dog toys", "cat toys", "pet toy"],
  "Pet Supplies::Chew Toys": ["dog chew toy", "chew toy"],
  "Pet Supplies::Scratching Posts": ["cat scratcher", "scratching post"],
  "Pet Supplies::Cat Litter": ["kitty litter"],
  "Pet Supplies::Litter Boxes": ["cat litter box", "litter box"],
  "Pet Supplies::Litter Scoops": ["cat litter scoop", "litter scoop"],
  "Pet Supplies::Pet Bowls": ["dog bowl", "cat bowl", "pet bowl"],
  "Pet Supplies::Pet Feeders": ["automatic pet feeder", "pet feeder"],
  "Pet Supplies::Pet Water Dispensers": ["pet water fountain", "pet water dispenser"],
  "Pet Supplies::Aquariums": ["aquarium"],
  "Pet Supplies::Aquarium Filters": ["fish tank filter", "aquarium filter"],
  "Pet Supplies::Aquarium Decorations": ["fish tank decor", "aquarium decoration"],
  "Pet Supplies::Aquarium Pumps": ["fish tank pump", "aquarium pump"],
  "Pet Supplies::Aquarium Lighting": ["fish tank light"],
  "Pet Supplies::Bird Cages": ["bird cage"],
  "Pet Supplies::Dog Cages": ["dog crate", "dog cage"],
  "Pet Supplies::Pet Carriers": ["animal carrier", "pet carrier"],
  "Pet Supplies::Pet Training": ["dog training"],
  "Pet Supplies::Pet Cleaning Supplies": ["pet cleanup supplies", "pet cleaning supply"],

  // CLOTHING & ACCESSORIES
  "Clothing & Accessories::Shirts": ["shirt"],
  "Clothing & Accessories::T-Shirts": ["tshirts", "tee shirts", "tees", "t shirts", "t-shirt"],
  "Clothing & Accessories::Polo Shirts": ["polo shirt"],
  "Clothing & Accessories::Blouses": ["blouse"],
  "Clothing & Accessories::Dresses": ["dress"],
  "Clothing & Accessories::Skirts": ["skirt"],
  "Clothing & Accessories::Jeans": ["jean"],
  "Clothing & Accessories::Pants": ["pant"],
  "Clothing & Accessories::Shorts": ["short"],
  "Clothing & Accessories::Leggings": ["legging"],
  "Clothing & Accessories::Jackets": ["jacket"],
  "Clothing & Accessories::Coats": ["coat"],
  "Clothing & Accessories::Sweaters": ["sweater"],
  "Clothing & Accessories::Hoodies": ["hoody"],
  "Clothing & Accessories::Undergarments": ["underwear", "undergarment"],
  "Clothing & Accessories::Bras": ["bra"],
  "Clothing & Accessories::Panties": ["panty"],
  "Clothing & Accessories::Boxers": ["boxer"],
  "Clothing & Accessories::Socks": ["sock"],
  "Clothing & Accessories::Sleepwear": ["nightwear", "pajamas"],
  "Clothing & Accessories::Swimwear": ["swimsuit", "bathing suit"],
  "Clothing & Accessories::Activewear": ["sportswear", "athletic wear"],
  "Clothing & Accessories::School Uniforms": ["school uniform"],
  "Clothing & Accessories::Work Uniforms": ["work uniform"],
  "Clothing & Accessories::Children's Clothing": ["childrens clothing", "kids clothing"],
  "Clothing & Accessories::Maternity Wear": ["maternity clothing"],
  "Clothing & Accessories::Shoes": ["shoe"],
  "Clothing & Accessories::Sandals": ["sandal"],
  "Clothing & Accessories::Slippers": ["slipper"],
  "Clothing & Accessories::Boots": ["boot"],
  "Clothing & Accessories::Sneakers": ["sneaker"],
  "Clothing & Accessories::Heels": ["heel"],
  "Clothing & Accessories::Caps": ["cap"],
  "Clothing & Accessories::Hats": ["hat"],
  "Clothing & Accessories::Belts": ["belt"],
  "Clothing & Accessories::Wallets": ["wallet"],
  "Clothing & Accessories::Handbags": ["handbag", "purse"],
  "Clothing & Accessories::Luggage": ["luggage"],
  "Clothing & Accessories::Scarves": ["scarf"],
  "Clothing & Accessories::Gloves": ["glove"],
  "Clothing & Accessories::Jewelry": ["jewelry"],
  "Clothing & Accessories::Necklaces": ["necklace"],
  "Clothing & Accessories::Bracelets": ["bracelet"],
  "Clothing & Accessories::Rings": ["ring"],
  "Clothing & Accessories::Earrings": ["earring"],
  "Clothing & Accessories::Watches": ["watch"],
  "Clothing & Accessories::Sunglasses": ["sun glasses", "sunglass"],
  "Clothing & Accessories::Fashion Accessories": ["fashion accessory"],

  // KITCHEN & DINING
  "Kitchen & Dining::Cookware": ["cookware"],
  "Kitchen & Dining::Frying Pans": ["frying pan", "skillet"],
  "Kitchen & Dining::Saucepans": ["saucepan"],
  "Kitchen & Dining::Stock Pots": ["stockpot", "cooking pot", "stock pot"],
  "Kitchen & Dining::Bakeware": ["bakeware"],
  "Kitchen & Dining::Baking Trays": ["baking sheet", "baking tray"],
  "Kitchen & Dining::Cake Pans": ["cake tin", "cake pan"],
  "Kitchen & Dining::Mixing Bowls": ["mixing bowl"],
  "Kitchen & Dining::Measuring Cups": ["measuring cup"],
  "Kitchen & Dining::Measuring Spoons": ["measuring spoon"],
  "Kitchen & Dining::Kitchen Utensils": ["cooking utensils", "kitchen utensil"],
  "Kitchen & Dining::Spatulas": ["spatula"],
  "Kitchen & Dining::Ladles": ["ladle"],
  "Kitchen & Dining::Tongs": ["tong"],
  "Kitchen & Dining::Whisks": ["whisk"],
  "Kitchen & Dining::Can Openers": ["can opener"],
  "Kitchen & Dining::Bottle Openers": ["bottle opener"],
  "Kitchen & Dining::Knives": ["knife"],
  "Kitchen & Dining::Knife Sets": ["knife set"],
  "Kitchen & Dining::Cutting Boards": ["chopping board", "cutting board"],
  "Kitchen & Dining::Kitchen Shears": ["kitchen scissors", "kitchen shear"],
  "Kitchen & Dining::Graters": ["grater"],
  "Kitchen & Dining::Peelers": ["peeler"],
  "Kitchen & Dining::Colanders": ["colander"],
  "Kitchen & Dining::Strainers": ["strainer"],
  "Kitchen & Dining::Food Containers": ["food container"],
  "Kitchen & Dining::Food Storage": ["food storage products"],
  "Kitchen & Dining::Lunch Containers": ["lunch box", "food lunch container", "lunch container"],
  "Kitchen & Dining::Tumblers": ["tumbler"],
  "Kitchen & Dining::Mugs": ["mug"],
  "Kitchen & Dining::Cups": ["cup"],
  "Kitchen & Dining::Glasses": ["glass"],
  "Kitchen & Dining::Plates": ["plate"],
  "Kitchen & Dining::Bowls": ["bowl"],
  "Kitchen & Dining::Serving Platters": ["serving platter"],
  "Kitchen & Dining::Serving Trays": ["serving tray"],
  "Kitchen & Dining::Serving Utensils": ["serving tools", "serving utensil"],
  "Kitchen & Dining::Dinnerware": ["dinnerware"],
  "Kitchen & Dining::Flatware": ["cutlery"],
  "Kitchen & Dining::Spoons": ["spoon"],
  "Kitchen & Dining::Forks": ["fork"],
  "Kitchen & Dining::Chopsticks": ["chopstick"],
  "Kitchen & Dining::Table Knives": ["dinner knives", "table knife"],
  "Kitchen & Dining::Tablecloths": ["table cloth", "tablecloth"],
  "Kitchen & Dining::Placemats": ["place mats", "placemat"],
  "Kitchen & Dining::Napkins": ["napkin"],
  "Kitchen & Dining::Kitchen Towels": ["dish towels", "tea towels", "kitchen towel"],
  "Kitchen & Dining::Oven Mitts": ["oven gloves", "oven mitt"],

  // HOME & LIVING
  "Home & Living::Furniture": ["furniture"],
  "Home & Living::Sofas": ["sofa"],
  "Home & Living::Chairs": ["chair"],
  "Home & Living::Tables": ["table"],
  "Home & Living::Dining Tables": ["dining table"],
  "Home & Living::Coffee Tables": ["coffee table"],
  "Home & Living::Beds": ["bed"],
  "Home & Living::Mattresses": ["mattress"],
  "Home & Living::Bed Frames": ["bed frame"],
  "Home & Living::Wardrobes": ["wardrobe"],
  "Home & Living::Bookcases": ["bookcase"],
  "Home & Living::Storage Boxes": ["storage box"],
  "Home & Living::Storage Baskets": ["storage basket"],
  "Home & Living::Closet Organizers": ["wardrobe organizer", "closet organizer"],
  "Home & Living::Blinds": ["blind"],
  "Home & Living::Rugs": ["rug"],
  "Home & Living::Doormats": ["door mat", "doormat"],
  "Home & Living::Pillows": ["pillow"],
  "Home & Living::Cushions": ["cushion"],
  "Home & Living::Bedsheets": ["bed sheets", "bed linen", "bedsheet"],
  "Home & Living::Blankets": ["blanket"],
  "Home & Living::Comforters": ["comforter"],
  "Home & Living::Quilts": ["quilt"],
  "Home & Living::Mattress Protectors": ["mattress cover", "mattress protector"],
  "Home & Living::Decorations": ["decoration"],
  "Home & Living::Wall Art": ["wall decor"],
  "Home & Living::Picture Frames": ["photo frames", "picture frame"],
  "Home & Living::Vases": ["vase"],
  "Home & Living::Artificial Plants": ["fake plants", "artificial plant"],
  "Home & Living::Indoor Plants": ["house plants", "indoor plant"],
  "Home & Living::Clocks": ["clock"],
  "Home & Living::Lamps": ["lamp"],
  "Home & Living::Table Lamps": ["desk lamps", "table lamp"],
  "Home & Living::Floor Lamps": ["standing lamps", "floor lamp"],
  "Home & Living::Ceiling Lights": ["ceiling lamp", "ceiling light"],
  "Home & Living::LED Strips": ["led strip lights", "led strip", "light emitting diode strips"],
  "Home & Living::Diffusers": ["diffuser"],
  "Home & Living::Home Fragrance": ["room fragrance"],
  "Home & Living::Laundry Hampers": ["laundry hamper"],
  "Home & Living::Shoe Racks": ["shoe organizer", "shoe rack"],

  // SPORTS & OUTDOORS
  "Sports & Outdoors::Basketballs": ["basketball"],
  "Sports & Outdoors::Volleyballs": ["volleyball"],
  "Sports & Outdoors::Footballs": ["football"],
  "Sports & Outdoors::Soccer Balls": ["football", "soccer ball"],
  "Sports & Outdoors::Baseballs": ["baseball"],
  "Sports & Outdoors::Softballs": ["softball"],
  "Sports & Outdoors::Badminton Rackets": ["badminton racket", "badminton racquet"],
  "Sports & Outdoors::Badminton Shuttlecocks": ["shuttlecock", "shuttle", "badminton shuttlecock"],
  "Sports & Outdoors::Tennis Rackets": ["tennis racket", "tennis racquet"],
  "Sports & Outdoors::Tennis Balls": ["tennis ball"],
  "Sports & Outdoors::Table Tennis Paddles": ["ping pong paddle", "table tennis paddle"],
  "Sports & Outdoors::Table Tennis Balls": ["ping pong balls", "table tennis ball"],
  "Sports & Outdoors::Golf Clubs": ["golf club"],
  "Sports & Outdoors::Golf Balls": ["golf ball"],
  "Sports & Outdoors::Boxing Gloves": ["boxing glove"],
  "Sports & Outdoors::Punching Bags": ["punch bag", "punching bag"],
  "Sports & Outdoors::Protective Gear": ["safety gear"],
  "Sports & Outdoors::Helmets": ["helmet"],
  "Sports & Outdoors::Knee Pads": ["knee guards", "knee pad"],
  "Sports & Outdoors::Elbow Pads": ["elbow guards", "elbow pad"],
  "Sports & Outdoors::Sports Bags": ["gym bag", "sports bag"],
  "Sports & Outdoors::Sports Bottles": ["sports water bottle", "sports bottle"],
  "Sports & Outdoors::Fitness Equipment": ["gym equipment", "exercise equipment"],
  "Sports & Outdoors::Dumbbells": ["dumbbell"],
  "Sports & Outdoors::Barbells": ["barbell"],
  "Sports & Outdoors::Weight Plates": ["weight plate"],
  "Sports & Outdoors::Resistance Bands": ["exercise bands", "resistance band"],
  "Sports & Outdoors::Yoga Mats": ["exercise mat", "yoga mat"],
  "Sports & Outdoors::Yoga Blocks": ["yoga brick", "yoga block"],
  "Sports & Outdoors::Jump Ropes": ["skipping rope", "jump rope"],
  "Sports & Outdoors::Exercise Bikes": ["stationary bike", "exercise bike"],
  "Sports & Outdoors::Treadmills": ["treadmill"],
  "Sports & Outdoors::Camping Tents": ["tent", "camping tent"],
  "Sports & Outdoors::Sleeping Bags": ["sleeping bag"],
  "Sports & Outdoors::Camping Chairs": ["folding camping chair", "camping chair"],
  "Sports & Outdoors::Camping Tables": ["folding camping table", "camping table"],
  "Sports & Outdoors::Flashlights": ["flashlight"],
  "Sports & Outdoors::Lanterns": ["lantern"],
  "Sports & Outdoors::Coolers": ["cooler"],
  "Sports & Outdoors::Picnic Supplies": ["picnic accessories", "picnic supply"],
  "Sports & Outdoors::Hiking Backpacks": ["hiking bag", "hiking backpack"],
  "Sports & Outdoors::Trekking Poles": ["hiking poles", "trekking pole"],
  "Sports & Outdoors::Fishing Rods": ["fishing pole", "fishing rod"],
  "Sports & Outdoors::Fishing Reels": ["fishing reel"],
  "Sports & Outdoors::Fishing Lines": ["fishing line"],
  "Sports & Outdoors::Fishing Hooks": ["fish hooks", "fishing hook"],
  "Sports & Outdoors::Fishing Baits": ["fishing bait", "lures"],
  "Sports & Outdoors::Life Jackets": ["life vest", "life jacket"],
  "Sports & Outdoors::Swimming Goggles": ["swim goggles", "swimming goggle"],
  "Sports & Outdoors::Swimming Caps": ["swim cap", "swimming cap"],
  "Sports & Outdoors::Beach Accessories": ["beach gear", "beach accessory"],
  "Sports & Outdoors::Bicycles": ["bicycle"],
  "Sports & Outdoors::Bike Helmets": ["bicycle helmet", "bike helmet"],
  "Sports & Outdoors::Bike Accessories": ["bicycle accessories", "bike accessory"],

  // TOYS & GAMES
  "Toys & Games::Action Figures": ["action figure"],
  "Toys & Games::Dolls": ["doll"],
  "Toys & Games::Stuffed Toys": ["plush toys", "stuffed animals", "stuffed toy"],
  "Toys & Games::Building Blocks": ["toy blocks", "building block"],
  "Toys & Games::Construction Toys": ["building toys", "construction toy"],
  "Toys & Games::Toy Cars": ["toy car"],
  "Toys & Games::Toy Trucks": ["toy truck"],
  "Toys & Games::Toy Trains": ["toy train"],
  "Toys & Games::Remote Control Toys": ["rc toys", "remote controlled toys", "remote control toy"],
  "Toys & Games::Educational Toys": ["educational toy"],
  "Toys & Games::Learning Toys": ["learning toy"],
  "Toys & Games::Board Games": ["board game"],
  "Toys & Games::Card Games": ["card game"],
  "Toys & Games::Puzzles": ["puzzle"],
  "Toys & Games::Jigsaw Puzzles": ["jigsaw puzzle"],
  "Toys & Games::Chess Sets": ["chess set"],
  "Toys & Games::Checkers": ["checker"],
  "Toys & Games::Rubik's Cubes": ["rubiks cube", "rubik cube", "rubiks cubes", "rubik's cube"],
  "Toys & Games::Musical Toys": ["music toys", "musical toy"],
  "Toys & Games::Toy Instruments": ["toy musical instruments", "toy instrument"],
  "Toys & Games::Pretend Play": ["role play toys"],
  "Toys & Games::Kitchen Playsets": ["toy kitchen", "kitchen playset"],
  "Toys & Games::Doctor Playsets": ["doctor kit toy", "doctor playset"],
  "Toys & Games::Tool Playsets": ["toy tool set", "tool playset"],
  "Toys & Games::Outdoor Toys": ["outside toys", "outdoor toy"],
  "Toys & Games::Water Guns": ["water pistol", "water gun"],
  "Toys & Games::Kites": ["kite"],
  "Toys & Games::Bubbles": ["bubble"],
  "Toys & Games::Play Dough": ["playdough", "modeling clay"],
  "Toys & Games::Slime": ["slime"],
  "Toys & Games::Arts & Crafts": ["arts and crafts", "craft supplies", "arts & craft"],
  "Toys & Games::Coloring Books": ["colouring books", "coloring book"],
  "Toys & Games::Toy Storage": ["toy organizer"],
  "Toys & Games::Collectibles": ["collectible"],
  "Toys & Games::Trading Cards": ["collectible cards", "trading card"],
  "Toys & Games::Video Games": ["video game"],
  "Toys & Games::Gaming Consoles": ["game console", "gaming console"],
  "Toys & Games::Gaming Accessories": ["game accessories", "gaming accessory"],

  // GARDEN & AGRICULTURE
  "Garden & Agriculture::Garden Soil": ["topsoil", "gardening soil"],
  "Garden & Agriculture::Potting Mix": ["potting soil"],
  "Garden & Agriculture::Compost": ["compost"],
  "Garden & Agriculture::Fertilizers": ["fertilizer"],
  "Garden & Agriculture::Organic Fertilizers": ["organic fertilizer"],
  "Garden & Agriculture::Chemical Fertilizers": ["synthetic fertilizer", "chemical fertilizer"],
  "Garden & Agriculture::Seeds": ["seed"],
  "Garden & Agriculture::Vegetable Seeds": ["vegetable seed"],
  "Garden & Agriculture::Flower Seeds": ["flower seed"],
  "Garden & Agriculture::Fruit Seeds": ["fruit seed"],
  "Garden & Agriculture::Seedlings": ["seedling"],
  "Garden & Agriculture::Pesticides": ["pesticide"],
  "Garden & Agriculture::Herbicides": ["herbicide"],
  "Garden & Agriculture::Fungicides": ["fungicide"],
  "Garden & Agriculture::Plant Nutrients": ["plant food", "plant nutrient"],
  "Garden & Agriculture::Plant Pots": ["flower pots", "plant pot"],
  "Garden & Agriculture::Planters": ["planter"],
  "Garden & Agriculture::Seed Trays": ["seedling trays", "seed tray"],
  "Garden & Agriculture::Hose Nozzles": ["hose nozzle"],
  "Garden & Agriculture::Sprinklers": ["sprinkler"],
  "Garden & Agriculture::Irrigation Supplies": ["irrigation equipment", "irrigation supply"],
  "Garden & Agriculture::Garden Gloves": ["gardening gloves", "garden glove"],
  "Garden & Agriculture::Garden Shovels": ["garden shovel"],
  "Garden & Agriculture::Garden Rakes": ["garden rake"],
  "Garden & Agriculture::Chainsaws": ["chainsaw"],
  "Garden & Agriculture::Leaf Blowers": ["leaf blower"],
  "Garden & Agriculture::Greenhouses": ["greenhouse"],
  "Garden & Agriculture::Livestock Feed": ["animal feed"],
  "Garden & Agriculture::Poultry Feed": ["chicken feed"],
  "Garden & Agriculture::Animal Supplements": ["livestock supplements", "animal supplement"],
  "Garden & Agriculture::Farm Tools": ["farming tools", "farm tool"],
  "Garden & Agriculture::Agricultural Equipment": ["farm equipment"],

  // PARTY & EVENTS
  "Party & Events::Balloons": ["balloon"],
  "Party & Events::Balloon Accessories": ["balloon supplies", "balloon accessory"],
  "Party & Events::Party Hats": ["party hat"],
  "Party & Events::Party Decorations": ["party decor", "party decoration"],
  "Party & Events::Banners": ["banner"],
  "Party & Events::Streamers": ["streamer"],
  "Party & Events::Confetti": ["confetti"],
  "Party & Events::Cake Toppers": ["cake topper"],
  "Party & Events::Birthday Candles": ["cake candles", "birthday candle"],
  "Party & Events::Gift Wrap": ["wrapping paper"],
  "Party & Events::Gift Bags": ["gift bag"],
  "Party & Events::Gift Boxes": ["gift box"],
  "Party & Events::Gift Ribbons": ["gift ribbon"],
  "Party & Events::Greeting Cards": ["greeting card"],
  "Party & Events::Invitations": ["invitation"],
  "Party & Events::Table Covers": ["tablecloth", "table cover"],
  "Party & Events::Party Favors": ["party giveaways", "party favor"],
  "Party & Events::Photo Booth Props": ["photobooth props", "photo booth prop"],
  "Party & Events::Costumes": ["costume"],
  "Party & Events::Masks": ["mask"],
  "Party & Events::Event Decorations": ["event decor", "event decoration"],
  "Party & Events::Wedding Supplies": ["wedding accessories", "wedding supply"],
  "Party & Events::Baby Shower Supplies": ["baby shower decorations", "baby shower supply"],
  "Party & Events::Christmas Decorations": ["christmas decor", "christmas decoration"],
  "Party & Events::Halloween Decorations": ["halloween decor", "halloween decoration"],

  // BOOKS & MEDIA
  "Books & Media::Books": ["book"],
  "Books & Media::Novels": ["novel"],
  "Books & Media::Textbooks": ["textbook"],
  "Books & Media::Reference Books": ["reference book"],
  "Books & Media::Children's Books": ["childrens books", "kids books", "children's book"],
  "Books & Media::Comic Books": ["comics", "comic book"],
  "Books & Media::Magazines": ["magazine"],
  "Books & Media::Newspapers": ["newspaper"],
  "Books & Media::Journals": ["journal"],
  "Books & Media::Planners": ["planner"],
  "Books & Media::Calendars": ["calendar"],
  "Books & Media::Maps": ["map"],
  "Books & Media::DVDs": ["dvd", "digital video discs"],
  "Books & Media::Blu-rays": ["bluray", "blu ray", "blu rays", "blu-ray"],
  "Books & Media::Music CDs": ["audio cds", "compact discs", "music cd", "music compact discs"],
  "Books & Media::Vinyl Records": ["vinyl albums", "vinyl record"],
  "Books & Media::Gift Cards": ["gift voucher", "gift card"],

  // TOBACCO ACCESSORIES
  "Tobacco Accessories::Cigarettes": ["cigarette"],
  "Tobacco Accessories::Cigars": ["cigar"],
  "Tobacco Accessories::Rolling Papers": ["cigarette papers", "rolling paper"],
  "Tobacco Accessories::Cigarette Filters": ["filter tips", "cigarette filter"],
  "Tobacco Accessories::Ashtrays": ["ashtray"],
  "Tobacco Accessories::Cigarette Cases": ["cigarette holder case", "cigarette case"],
  "Tobacco Accessories::Humidors": ["humidor"],
  "Tobacco Accessories::Pipe Tobacco": ["smoking tobacco"],
  "Tobacco Accessories::Smoking Pipes": ["tobacco pipe", "smoking pipe"],

  // RELIGIOUS & CULTURAL ITEMS
  "Religious & Cultural Items::Bibles": ["bible"],
  "Religious & Cultural Items::Prayer Books": ["prayer book"],
  "Religious & Cultural Items::Rosaries": ["rosary"],
  "Religious & Cultural Items::Crosses": ["cross"],
  "Religious & Cultural Items::Religious Statues": ["saint statues", "religious statue"],
  "Religious & Cultural Items::Incense": ["incense"],
  "Religious & Cultural Items::Incense Holders": ["incense burner", "incense holder"],
  "Religious & Cultural Items::Holy Water Bottles": ["holy water container", "holy water bottle"],
  "Religious & Cultural Items::Religious Jewelry": ["religious jewellery"],
  "Religious & Cultural Items::Offering Envelopes": ["church offering envelopes", "offering envelope"],
  "Religious & Cultural Items::Religious Decorations": ["religious decor", "religious decoration"],
  "Religious & Cultural Items::Cultural Decorations": ["cultural decor", "cultural decoration"],
  "Religious & Cultural Items::Festival Supplies": ["festival decorations", "festival supply"],

  // SERVICES & FEES
  "Services & Fees::Delivery Fees": ["delivery fee", "delivery charge"],
  "Services & Fees::Service Charges": ["service charge"],
  "Services & Fees::Membership Fees": ["membership fee"],
  "Services & Fees::Subscriptions": ["subscription"],
  "Services & Fees::Gift Wrapping": ["gift wrap service"],
  "Services & Fees::Installation Services": ["installation fee", "installation service"],
  "Services & Fees::Repair Services": ["repair fee", "repair service"],
  "Services & Fees::Warranty Services": ["warranty fee", "warranty service"],
  "Services & Fees::Rental Fees": ["rental fee"],
  "Services & Fees::Processing Fees": ["processing fee"],
  "Services & Fees::Shipping Fees": ["shipping fee", "freight charge"],
  "Services & Fees::Convenience Fees": ["convenience fee"],

  // OTHER
  "Other::Uncategorized": ["uncategorised", "no category"],
  "Other::Miscellaneous": ["misc", "assorted items"],
  "Other::Unknown": ["unidentified"],
  "Other::Custom Items": ["custom product", "custom item"],
  "Other::Seasonal Items": ["seasonal product", "seasonal item"],
  "Other::Limited Edition": ["limited-edition"],
  "Other::Promotional Items": ["promo items", "promotional item"],
  "Other::Bundles": ["bundle pack", "product bundle", "bundle"],
  "Other::Clearance Items": ["clearance products", "clearance item"],
  "Other::Refurbished Items": ["refurbished products", "refurbished item"],

};